### ISSUE TITLE
nauty 2.8.6 is buggy (request to revert to nauty 2.7r4)

### ISSUE THREAD

**Issue by GMS103** [Homebrew/homebrew-core#125101]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: b1ef41c25d12795dc93975e337e8644d0974b53c
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43c39073420de6975f20ac96e98dc822338a3df3
Core tap last commit: 3 weeks ago
Core tap branch: master
Core tap JSON: 07 Mar 09:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.chmoWCRLjQ/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.7.4-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false
% brew doctor
Your system is ready to brew.
%
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

(This is my first report, please forgive me if it is not correct.)
After ```brew update``` I got
```
% brew info nauty
==> nauty: stable 2.8.6 (bottled)
Automorphism groups of graphs and digraphs
https://pallini.di.uniroma1.it/
/opt/homebrew/Cellar/nauty/2.8.6 (79 files, 9.1MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-02-18 at 16:54:53
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nauty.rb
License: Apache-2.0
==> Analytics
install: 119 (30 days), 311 (90 days), 1,283 (365 days)
install-on-request: 77 (30 days), 140 (90 days), 626 (365 days)
build-error: 0 (30 days)
```
The problem is that this version of nauty is buggy.  One should get
```
% gentreeg 2 |& grep "Z 1 trees"
>Z 1 trees generated in 0.00 sec
```
whereas with 2.8.6 there will be no output.
So this is a request to revert to the previous version (nauty 2.7r4).

### What happened (include all command output)?

See above.

### What did you expect to happen?

See above.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by carlocab** [comment]
Should be fixed. Give it about half an hour, then do
```sh
brew update && brew upgrade nauty
```

**Comment by GMS103** [comment]
I still get some unexpected results with the patched nauty from Homebrew (version 2.8.6_1).
```
% brew info nauty
==> nauty: stable 2.8.6 (bottled)
Automorphism groups of graphs and digraphs
https://pallini.di.uniroma1.it/
/opt/homebrew/Cellar/nauty/2.8.6_1 (79 files, 9.1MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-03-08 at 19:57:40
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nauty.rb
License: Apache-2.0
==> Analytics
install: 119 (30 days), 311 (90 days), 1,283 (365 days)
install-on-request: 77 (30 days), 140 (90 days), 626 (365 days)
build-error: 0 (30 days)
```
It gives
```
% gentreeg 2
>A gentreeg Z=0:0 D=0 n=0
:An
>Z 1 trees generated in 0.00 sec
% gentreeg 3
>A gentreeg Z=0:0 D=0 n=0
:Bc
>Z 1 trees generated in 0.00 sec
% gentreeg 4
>A gentreeg Z=0:0 D=0 n=0
:Cdf
:Ccf
>Z 2 trees generated in 0.00 sec
% 
```
which does not seem correct to me.

**Comment by GMS103** [comment]
Sorry, my mistake (meaning of ```Z``` has changed).
Thanks Carlo and Dima for your quick reactions.
