### ISSUE TITLE
git send-email with brewed perl (and SSL) is broken

### ISSUE THREAD

**Issue by iokill** [Homebrew/homebrew-core#12870]
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
$ brew gist-logs git
https://gist.github.com/15321e136ef6377464259a3b92f6917d
```

Hi!

I'm tried to use `git send-email` with having perl installed via homebrew. The error I'm getting is the well known `Net::SMTP::SSL` problem [[1](http://stackoverflow.com/questions/21306937/using-git-send-mail-but-i-am-getting-an-error)] [[2](https://gist.github.com/relaxdiego/be7b87cae8c2d51d5ee4)] [[3](https://www.tollmanz.com/git-send-email-gmail-os-x/)]:

```
$ git send-email ...
<snip>
Can't locate Net/SMTP/SSL.pm in @INC (you may need to install the Net::SMTP::SSL module) 
(@INC contains: /usr/local/Cellar/git/2.12.2/lib/perl5/site_perl 
/Applications/Xcode.app/Contents/Developer/Library/Perl/5.18/darwin-thread-multi-2level 
/Library/Developer/CommandLineTools/Library/Perl/5.18/darwin-thread-multi-2level 
/Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 
/Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 
/Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level 
/System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level 
/System/Library/Perl/Extras/5.18 .) at /usr/local/Cellar/git/2.12.2/libexec/git-core/git-send-email 
line 1386.
```

However, simply installing `Net::SMTP::SSL` does not work since that seems to be installed into a path where `git send-email`is not looking for it:

```
$ sudo -H cpan Net::SMTP::SSL
<snip>
Manifying 1 pod document
Installing /usr/local/Cellar/perl/5.24.1/lib/perl5/site_perl/5.24.1/Net/SMTP/SSL.pm
Installing /usr/local/Cellar/perl/5.24.1/share/man/man3/Net::SMTP::SSL.3
Appending installation info to /usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/perllocal.pod
  RJBS/Net-SMTP-SSL-1.04.tar.gz
  /usr/bin/make install  -- OK
```

I'm no expert on perl and its modules, but it looks to me like the formula for git should detect the brewed version of perl and properly set the include path for all of git's perl scripts.

If there is a better/simpler solution it would be great if some could point me in the that direction. :) Also adding a caveat to the git formula would be great.

Thanks!
David

**Comment by JCount** [comment]
@iokill See if the patch I just pushed fixes it if you build using the `--with-brewed-openssl` formula option.

**Comment by iokill** [comment]
@JCount Just tried it. Unfortunately no change. I still get the same error `Can't locate Net/SMTP/SSL.pm in @INC ...`

**Comment by JCount** [comment]
@iokill The openssl issue in the git formula may have been a bit of a red herring. Try installing git using 'brew install git --with-brewed-curl --with-brewed-openssl **--with-brewed-svn**'

Now, you may wonder why you would need brew's svn to use `git send-mail`. You don't really, it is just a really bad workaround to get your git install to work with brew's perl, rather than the system perl. This **_probably_** will work, but it is a really bad way of getting the current formula to build using brew's perl. Hopefully, using brewed svn will not be an issue for you, and this will work temporarily while a better, more permanent, solution is found.

**Comment by iokill** [comment]
@JCount sorry for taking so long to respond. I tried it and it did not change...

Looking at the second line in `/usr/local/Cellar/git/2.12.2/libexec/git-core/git-send-email` it looks to me like the path where `cpan` installs `Net::SMTP::SSL` is missing.

Currently, it looks like this for me (using `--with-brewed-curl --with-brewed-openssl --with-brewed-svn`):
```
#!/usr/bin/perl
use lib (split(/:/, $ENV{GITPERLLIB} || "/usr/local/Cellar/git/2.12.2/lib/perl5/site_perl:/usr/local/opt/subversion/lib/perl5/site_perl:/usr/local/opt/subversion/Library/Perl/5.18/darwin-thread-multi-2level"));
```

**Comment by DomT4** [comment]
I'll look into this.

**Comment by JCount** [comment]
Thanks @DomT4. It has been somewhat frustrating to try to pin down. 😸

**Comment by DomT4** [comment]
Yeah, I'm slightly confused how this is happening to you to be honest, because the only way I can break this is by changing the hashbang in that script to `#!/usr/bin/env perl`. I can tweak the formula to be more forgiving of non-system Perl's without much of an issue, but I'm not convinced this actually a formula issue yet 😕.

Can you run `mdfind SSL.pm` & `/usr/bin/perl -V` and provide the output of both?

**Comment by DomT4** [comment]
Setting `GITPERLLIB` to a garbage directory results in things blowing up as well. Check your `env` for that, although seems unlikely to be there without you knowing about it.

**Comment by ilovezfs** [comment]
ping @iokill regarding the questions from @DomT4

**Comment by DomT4** [comment]
Alright, lord, this took _quite some work_ but I indeed found the breakage under the default configuration. Geez. I think last night's [comment](https://github.com/Homebrew/homebrew-core/issues/12870#issuecomment-299595859) was an initial testing misconfiguration on my part. 

This basically seems to be broken out of the box, but indeed, having a custom/brewed `perl` means you need to give `git` some extra places to look. We can either support custom `perl`'s a little better or we can vendor some `perl` modules into the `git` formula.

One thing I would nudge on is that I really can't recommend enough not using the Cellar for `perl` modules. The `perl` formula has a caveat about this:

```
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.zshrc
```

**Comment by DomT4** [comment]
> We can either support custom perl's a little better 

This option is explored in https://github.com/Homebrew/homebrew-core/pull/13328.

**Comment by iokill** [comment]
@DomT4 thanks a lot for your effort and patches! I just tried them by reinstalling git with with `--with-perl` and it worked. 👍 

I also tried your hint with using perl's `local::lib`. This lead me to #13340. :-/
Anyways, after getting `local::lib` working, I was able to install `Net::SMTP::SSL` to `~/perl5` and everything works too.

FYI: **Without** your patches, but using `local::lib`, `git-send-email` finds `Net::SMTP::SSL`, but breaks afterwards:

```
$git send-email ...
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/iokill/perl5/lib/perl5/darwin-thread-multi-2level/auto/Net/SSLeay/SSLeay.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/iokill/perl5/lib/perl5/darwin-thread-multi-2level/auto/Net/SSLeay/SSLeay.bundle
  Expected in: flat namespace

error: git-send-email died of signal 6
```

But since it works with your patches this is no problem and this issue can be closed as soon as PR #13328 is merged. :D

Thanks!

**Comment by DomT4** [comment]
> FYI: Without your patches, but using local::lib, git-send-email finds Net::SMTP::SSL, but breaks afterwards:

Yeah, essentially with Perl if you build it using a newer major version don't expect to be able to run it using an older major version. Perl promises very little backwards compatibility in terms of major releases.
