### ISSUE TITLE
jmeter crahes when using openjdk bundled with the brew formula

### ISSUE THREAD

**Issue by sandrodz** [Homebrew/homebrew-core#150824]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  aws-sam-cli

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker-completion

HOMEBREW_VERSION: 4.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e57a87cfe9c15f192cd4fc6695a2b3b7acf0ddf7
Last commit: 3 days ago
Core tap JSON: 12 Oct 19:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use jmeter, but it crashes on start on Mac m1.

Related issue: https://github.com/apache/jmeter/issues/6083#issuecomment-1752536209

To fix jmeter crash, edit: `/opt/homebrew/Cellar/jmeter/5.6.2/bin/jmeter`

Changing this:

#!/bin/bash
JAVA_HOME="/opt/homebrew/opt/openjdk@17" exec "/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter"  "$@"

to this:

#!/bin/bash
exec "/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter"  "$@"

It will use my configured JDK instead of provided by Homebrew and it will not crash.

I think version that is linked by home-brew is not compatible.

### What happened (include all command output)?

jmeter failed to launch, jmeter crashes

### What did you expect to happen?

jmeter to launch

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install jmeter && jmeter
```

**Comment by Palayoub** [comment]
I got the same behaviour, thank your for pointing this out.

doing:
`$(brew --prefix openjdk)/bin/java --version`
outputs:
```
openjdk 21 2023-09-19
OpenJDK Runtime Environment Homebrew (build 21)
```

but when installing jmeter with brew: _brew install jmeter_ it downloads and installs the openjdk17.

I edited the _/opt/homebrew/Cellar/jmeter/5.6.2/bin/jmeter_ to point to my already installed jdk21 and it works.

**Comment by cho-m** [comment]
From data points, it sounds like Homebrew's `openjdk@17` on Sonoma is having issues.

I can reproduce issue. I have also confirmed that installing Ventura `openjdk@17` bottle works and using Sonoma `openjdk` bottle works.

So, it looks like something went wrong building `openjdk@17` bottle on Sonoma. May need to find out what difference is.

**Comment by cho-m** [comment]
Looks like reports are a bit mixed for `openjdk` 21 and some people have reported issues for other tools like VisualVM (https://github.com/oracle/visualvm/issues/528).

Not sure if anyone else has data points for OpenJDK built on macOS 14 Sonoma. I think most other distributions build on older macOS given common runners don't even support Sonoma (e.g. GitHub/Azure `macos-latest` is macOS 12 Monterey).

**Comment by Bo98** [comment]
This is a bug on Apple's part. OpenJDK relies on a framework shipped with macOS called JavaRuntimeSupport. It appears this framework triggers behaviour that causes this crash.

The reason you don't see this crash on other OpenJDK builds is because the crash is programmed to only happen when the program was built against the macOS 14 SDK. Many vendors haven't updated their build systems yet and distribute one macOS build. We distribute several macOS builds per OS version built with the corresponding SDK, so we would naturally be the first one hit by this issue.

**Comment by sandrodz** [comment]
@Bo98 can someone report this to Apple?

**Comment by Bo98** [comment]
Done so as FB13297978

**Comment by Bo98** [comment]
For now, what we might do is remove Sonoma bottles from OpenJDK. To do that, we will however need to come up with a minimal reproducible code that triggers the crash that we could add to our OpenJDK test. I don't have Sonoma-compatible hardware so I'm unable to do this currently.

**Comment by tsmock** [comment]
It needs to have something added to the menu bar.


```java
import javax.swing.*;
public class Test {
    public static void main(String... args) throws Exception {
        System.setProperty("apple.laf.useScreenMenuBar", "true");
        JFrame frame = new JFrame("Test Frame"); 
        JMenuBar menuBar = new JMenuBar();
        JMenu menu = new JMenu();
        JPanel panel = new JPanel();
        panel.add(new JLabel("Test"));
        frame.setJMenuBar(menuBar);
        menuBar.add(menu);
        frame.add(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
}
```

**Comment by Firefishy** [comment]
Also had the same crash with JOSM and the homebrew OpenJDK.

**Comment by karlvr** [comment]
For anyone suffering who wants a quick and probably temporary fix, dropping this code into some JNI removes the problematic method from `JRSMenu` _seemingly_ without any ill effects:

```objectivec
#import <objc/runtime.h>

void fixJavaRuntimeSupport() {
    Class jrsMenuClass = NSClassFromString(@"JRSMenu");
    if (jrsMenuClass) {
        Method originalMethod = class_getInstanceMethod(jrsMenuClass, @selector(installCarbonEventHandlers:));
        if (originalMethod) {
            IMP newImp = imp_implementationWithBlock(^(NSNotification *notification) {
                //            NSLog(@"Ignoring notification %@", notification);
            });
            class_replaceMethod(jrsMenuClass, @selector(installCarbonEventHandlers:), newImp, method_getTypeEncoding(originalMethod));
        }
    }
}
```

**Comment by Cnly** [comment]
Not sure if it's the same issue, but on my macOS 14.1 Ghidra constantly crashes with Homebrew's `openjdk 21.0.1 2023-10-17`. IIRC this started only after I upgraded the `openjdk` formulae a few days ago. Using the build with the same version number from jdk.java.net fixes the problem.

**Comment by liningpan** [comment]
I don't think this problem is resolved yet. I recently ran into this issue with plantuml.

**Comment by harischandraprasad** [comment]
I still have this issue with Mac Book Pro with Intel Chipset with Sonoma 14.1.2.

Error:
#  SIGILL (0x4) at pc=0x00007ff815f6dbc5, pid=98817, tid=259
#
# JRE version: OpenJDK Runtime Environment Homebrew (21.0.1) (build 21.0.1)
# Java VM: OpenJDK 64-Bit Server VM Homebrew (21.0.1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  [AppKit+0xc92bc5]  _NSCarbonMenuCrashIfNeeded+0x258

I did remove JMeter and installed a fresh and the latest(5.6.2) still has the same issue.

Please let me know if I need to capture any specific data to post here that will help.

**Comment by mirraj2** [comment]
I also had this issue with JVisualVM

**Comment by wudi** [comment]
+1

**Comment by melicerte** [comment]
> I got the same behaviour, thank your for pointing this out.
> 
> doing: `$(brew --prefix openjdk)/bin/java --version` outputs:
> 
> ```
> openjdk 21 2023-09-19
> OpenJDK Runtime Environment Homebrew (build 21)
> ```
> 
> but when installing jmeter with brew: _brew install jmeter_ it downloads and installs the **openjdk17**.
> 
> I edited the _/opt/homebrew/Cellar/jmeter/5.6.2/bin/jmeter_ to point to my already installed jdk21 and it works.

A full example would be nice :)

**Comment by MFurkanBabur** [comment]
I'm having the same problem and I couldn't solve it. When I solve it, I will write the result here.

**Comment by jrgrez** [comment]
I'm having the same problem here

**Comment by cho-m** [comment]
> Done so as FB13297978

@Bo98, do you know if this was fixed?

On OpenJDK side, there was a mention that this may have been included with macOS 14.2 - https://bugs.openjdk.org/browse/JDK-8319420. I don't think we rebuilt OpenJDK bottles since, but there are some open PRs that should allow us to rebuild with newer SDK.

**Comment by cho-m** [comment]
`openjdk` (21) is now built using newer macOS SDK (from Xcode 15.1).

For other JDKs, users may need to wait on open PRs (or we can try triggering a rebuild job if any PR gets stalled):
- #160094 
- #160095
- #160910

**Comment by Bo98** [comment]
> @Bo98, do you know if this was fixed?

Bug report with Apple is still open, but they may have forgotten to update it.

It does seem indeed fixed in macOS 14.2 - an exception to the crash has been added for JRSMenu. It should be a runtime change and thus not require rebuilds.

<img width="335" alt="Screenshot 2024-01-28 at 03 59 17" src="https://github.com/Homebrew/homebrew-core/assets/1190754/01fcb7c7-cf20-473d-bc12-30371250675b">
