### ISSUE TITLE
MacVim: Run into error after new formula

### ISSUE THREAD

**Issue by chuanconggao** [Homebrew/homebrew-core#15741]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Hi, I updated Homebrew and MacVim. Immediately, I see error message after running `mvim` on terminal:
```
Vim: Caught deadly signal SEGV
Vim: Finished.
```

The standalone version of MacVim also stopped working, with similar message. 

I have attached my `brew config` output:
```
HOMEBREW_VERSION: 1.2.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b5529084906af89827f6d9befd613457a1615918
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f3c0a237fc5a76c7ae02e2287c6c860f111d2fe0
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_131
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

My `brew doctor` output is clean.

**Comment by ilovezfs** [comment]
Ridiculous question but I'll ask anyway: did you try rebooting?

**Comment by chuanconggao** [comment]
@ilovezfs 

I just tried rebooting. It is the same. 

This all happens after I updated Python and MacVim. It seems the version bump for MacVim w.r.t. the Python PR of shadowing system executive did not work on my side. I tried switching to previous version of MacVim, and it works although without Python support.

BTW, I do not see where is it ridiculous. I run into an issue and report it. What is wrong with that?

**Comment by ilovezfs** [comment]
>BTW, I do not see where is it ridiculous. I run into an issue and report it. What is wrong with that?

Sorry for being unclear. I meant _my_ suggestion was ridiculous not your question.

>It seems the version bump for MacVim w.r.t. the Python PR of shadowing system executive did not work on my side.

Yes that could be it!

Try
```
export PATH=/usr/local/opt/python/libexec/bin:$PATH
```

**Comment by chuanconggao** [comment]
I should say sorry too for misunderstanding the sentence. Thanks for the clearing up. 

I have already tried adjusting the PATH variable. Still the same error message. 

BTW, the other formula for terminal based Vim works fine.

**Comment by ilovezfs** [comment]
Can you try rebuilding using master?
```
git -C $(brew --repo) checkout master
brew reinstall macvim
```

**Comment by chuanconggao** [comment]
Thanks for the quick reply. But still the same error.

**Comment by pirminis** [comment]
how to reset to the previous MacVim version using Homebrew?

**Comment by pirminis** [comment]
for now, this reverts me python + macvim versions to older ones:
```
ls /usr/local/Cellar/python
brew switch python 2.7.13
rm '/usr/local/bin/easy_install'
brew link --overwrite python

ls /usr/local/Cellar/macvim
brew switch macvim 8.0-134
```

**Comment by bertjwregeer** [comment]
It looks like something is causing Vim to be linked against both the system Python framework and the homebrew built Python framework:

```
$ otool -L /usr/local/Cellar/macvim/8.0-134_1/MacVim.app/Contents/MacOS/Vim  
/usr/local/Cellar/macvim/8.0-134_1/MacVim.app/Contents/MacOS/Vim:
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.64.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/libperl.dylib (compatibility version 5.18.0, current version 5.18.2)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1504.82.104)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 775.19.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1349.63.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

Specifically:
```
$ otool -L /usr/local/Cellar/macvim/8.0-134_1/MacVim.app/Contents/MacOS/Vim   | grep Python
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
```

Both can't be loaded at the same time...

**Comment by bertjwregeer** [comment]
Work-around:

```
$ brew uninstall --ignore-dependencies python
Uninstalling /usr/local/Cellar/python/2.7.13_1... (3,543 files, 48.5MB)
$ brew install --build-from-source macvim
==> Using the sandbox
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-134.tar.gz
Already downloaded: /Users/xistence/Library/Caches/Homebrew/macvim-8.0-134.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --with-tlib=ncurses --with-compiledby=Homebrew --with-local-dir=/usr/local --enable-cscope --enable-pythoninterp
==> make
🍺  /usr/local/Cellar/macvim/8.0-134_1: 2,133 files, 33.8MB, built in 1 minute 8 seconds
$ otool -L /usr/local/Cellar/macvim/8.0-134_1/MacVim.app/Contents/MacOS/Vim  | grep Python
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
```

Now MacVim works again.

**Comment by apuignav** [comment]
Having a similar problem, I've realized that in my case, when I install `python` I add `export PATH="/usr/local/opt/python/libexec/bin:$PATH"` to my `.zprofile`. However, this is not properly picked up from within `brew`: adding

```
odie `which python`
```

In the formula I get
```
Error: /usr/bin/python
```

All this can be fixed by changing `python` by `python2`, I think...

**Comment by ilovezfs** [comment]
@chuanconggao please try this:

```
cd $(brew --repo)
git reset --hard @^
export HOMEBREW_DEVELOPER=1
brew update
brew config
brew reinstall macvim
```

And see if that works.

Also, please post the `brew config` output here from the above steps.

**Comment by ilovezfs** [comment]
@apuignav ditto for you.

**Comment by ilovezfs** [comment]
>I reinstall macvim, but it doesn't work yet.

Can you please elaborate?

**Comment by ilovezfs** [comment]
Actually you need to do
```
brew reinstall -s macvim
```

**Comment by ilovezfs** [comment]
@chuanconggao I don't see your gist-logs for macvim.

**Comment by meritozh** [comment]
```
brew reinstall -s macvim --with-lua
```

```
otool -L /Applications/MacVim.app/Contents/MacOS/Vim
/Applications/MacVim.app/Contents/MacOS/Vim:
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.64.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/lua/lib/liblua.5.2.dylib (compatibility version 5.2.0, current version 5.2.4)
	/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/libperl.dylib (compatibility version 5.18.0, current version 5.18.2)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1504.82.104)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 775.19.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1349.63.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

```
brew config                        
HOMEBREW_VERSION: 1.2.4-85-gf2c2964
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: f2c2964cf78368b45ff9357d09c5ebe79c48104b
Last commit: 9 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: bd7f0aaf7b46e950e68237235058576430b8ab69
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_131
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

when open macvim:

```
Vim: Caught deadly signal SEGV
Vim: Finished.
```

**Comment by ilovezfs** [comment]
can you please post your gist-logs

**Comment by bertjwregeer** [comment]
@ilovezfs The problem is that MacVim is being linked against both the system Python and the Homebrew provided Python.

You can't link against both.

**Comment by ilovezfs** [comment]
@bertjwregeer ok, but I have yet to be able to reproduce any of these issues locally. Things seem fine. Feel free to open a PR if you know what the problem is.

**Comment by meritozh** [comment]
@ilovezfs 
https://gist.github.com/meritozh/26535bcb5721392d25998d5ef093dc48
@bertjwregeer 
but problem is why it will link both.

**Comment by bertjwregeer** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb#L73

This will run `python-config` and prepend the flags to `LDFLAGS`, the configure script also finds python2 if the homebrew python exists, and adds it's `LDFLAGS` as well.

**Comment by apuignav** [comment]
But `python -c` points to the system python, or at least for me, and this breaks everything

**Comment by ilovezfs** [comment]
@bertjwregeer if you build from master, then

```
/usr/local/opt/python/libexec/bin
```
is prepended to the PATH, which will point to brew's python's `python-config`. This behavior is only in master, which is why I asked people to try master above. And the problem still occurs with 1.2.4-85-gf2c2964 so I don't think that explains it.

```
iMac-TMP:~ joe$ ls -l /usr/local/opt/python/libexec/bin
total 72
lrwxr-xr-x  1 joe  admin  16 Dec 17  2016 2to3 -> ../../bin/2to3-2
lrwxr-xr-x  1 joe  admin  26 Dec 17  2016 easy_install -> ../../bin/easy_install-2.7
lrwxr-xr-x  1 joe  admin  15 Dec 17  2016 idle -> ../../bin/idle2
lrwxr-xr-x  1 joe  admin  14 Dec 17  2016 pip -> ../../bin/pip2
lrwxr-xr-x  1 joe  admin  16 Dec 17  2016 pydoc -> ../../bin/pydoc2
lrwxr-xr-x  1 joe  admin  17 Dec 17  2016 python -> ../../bin/python2
lrwxr-xr-x  1 joe  admin  24 Dec 17  2016 python-config -> ../../bin/python2-config
lrwxr-xr-x  1 joe  admin  18 Dec 17  2016 pythonw -> ../../bin/pythonw2
lrwxr-xr-x  1 joe  admin  19 Dec 17  2016 smtpd.py -> ../../bin/smtpd2.py
```

**Comment by bertjwregeer** [comment]
```checking --enable-pythoninterp argument... yes
checking for python2... /usr/local/opt/python/bin/python2
checking Python version... 2.7
checking Python is 2.3 or better... yep
checking Python's install prefix... /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7
checking Python's execution prefix... /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7
checking Python's configuration directory... /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config
checking Python's dll name... Python.framework/Versions/2.7/Python```

**Comment by ilovezfs** [comment]
Right, so macvim knows to look for python2, which is nice. Also, python and python2 will point to the same file, and python-config and python2-config will point to the same file, so I'm not seeing the problem yet.

**Comment by meritozh** [comment]
@apuiganv homebrew won't install `python` into */usr/local/bin* unless you modify `PATH`

**Comment by ilovezfs** [comment]
It will install `python2` which is how you should invoke it.

**Comment by bertjwregeer** [comment]
Okay, printing out the ENV after that python-config call:

```
HOMEBREW_PROCESSOR:Intel
HOMEBREW_DEV_CMD_RUN:1
HOMEBREW_USER_AGENT:Homebrew/1.2.4-85-gf2c2964 (Macintosh; Intel Mac OS X 10.12.6)
GEM_OLD_HOME:
TERM_PROGRAM:Apple_Terminal
HOMEBREW_COMMAND_DEPTH:1
HOMEBREW_LIBRARY:/usr/local/Homebrew/Library
SHELL:/bin/bash
TERM:xterm-256color
HOMEBREW_OS_VERSION:macOS 10.12.6
HOMEBREW_REPOSITORY:/usr/local/Homebrew
Apple_PubSub_Socket_Render:/private/tmp/com.apple.launchd.ZLOwpieStK/Render
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION:1
TERM_PROGRAM_VERSION:388.1.1
TERM_SESSION_ID:04ECD7C3-6F8E-43B2-9AAF-A7D4B6660673
HOMEBREW_RUBY_PATH:/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
HOMEBREW_GIT_CONFIG_FILE:/usr/local/Homebrew/.git/config
USER:xistence
TOX_PATH:
SSH_AUTH_SOCK:/private/tmp/com.apple.launchd.SufMMPFTib/Listeners
HOMEBREW_NO_AUTO_UPDATE:1
__CF_USER_TEXT_ENCODING:0x3E9:0x0:0x0
HOMEBREW_ANALYTICS_USER_UUID:9DC99146-305A-4AB8-8B0B-9BD6E71435A2
HOMEBREW_CACHE:/Users/xistence/Library/Caches/Homebrew
HOMEBREW_USER_AGENT_CURL:Homebrew/1.2.4-85-gf2c2964 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0
PATH:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cscope/bin:/usr/local/opt/python/bin:/usr/bin:/bin:/usr/sbin:/sbin
HOMEBREW_EDITOR:/usr/local/bin/vim
HOMEBREW_BREW_FILE:/usr/local/bin/brew
PWD:/usr/local/Homebrew
HOMEBREW_MACOS_VERSION:10.12.6
EDITOR:/usr/local/bin/vim
HOMEBREW_ANALYTICS_ID:UA-76679469-1
LANG:en_US.UTF-8
XPC_FLAGS:0x0
HOMEBREW_PRODUCT:Homebrew
XPC_SERVICE_NAME:0
SHLVL:1
HOME:/private/tmp/macvim-20170719-74898-1rgar7y/macvim-snapshot-134/.brew_home
GEM_OLD_PATH:
HOMEBREW_PREFIX:/usr/local
LOGNAME:xistence
PKG_CONFIG_PATH:/usr/local/opt/python/lib/pkgconfig
HOMEBREW_VERSION:1.2.4-85-gf2c2964
HOMEBREW_CELLAR:/usr/local/Cellar
HOMEBREW_CURL:/usr/bin/curl
DISPLAY:/private/tmp/com.apple.launchd.BqzWHWSUgi/org.macosforge.xquartz:0
SECURITYSESSIONID:186a5
HOMEBREW_SYSTEM:Macintosh
HOMEBREW_ERROR_PIPE:/tmp/homebrew20170719-74411-15qsmum/socket
OBJC:clang
CC:clang
HOMEBREW_CC:clang
OBJCXX:clang++
CXX:clang++
HOMEBREW_CXX:clang++
MAKEFLAGS:-j8
PKG_CONFIG_LIBDIR:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
HOMEBREW_CCCFG:sa
HOMEBREW_OPTIMIZATION_LEVEL:Os
HOMEBREW_OPT:/usr/local/opt
HOMEBREW_TEMP:/tmp
HOMEBREW_OPTFLAGS:-march=native
HOMEBREW_ARCHFLAGS:
CMAKE_PREFIX_PATH:/usr/local
CMAKE_FRAMEWORK_PATH:/usr/local/opt/python/Frameworks
CMAKE_INCLUDE_PATH:/usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
ACLOCAL_PATH:/usr/local/share/aclocal
HOMEBREW_ISYSTEM_PATHS:/usr/local/include:/usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
HOMEBREW_LIBRARY_PATHS:/usr/local/lib:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
HOMEBREW_DEPENDENCIES:cscope,python
HOMEBREW_FORMULA_PREFIX:/usr/local/Cellar/macvim/8.0-134_1
MACOSX_DEPLOYMENT_TARGET:10.12
SDKROOT:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
HOMEBREW_PREFER_CLT_PROXIES:1
TMPDIR:/tmp
TEMP:/tmp
TMP:/tmp
CURL_HOME:/Users/xistence
```

```
Sterling:Homebrew xistence$ /usr/local/opt/python/bin/python-config
-bash: /usr/local/opt/python/bin/python-config: No such file or directory
```

```
Sterling:Homebrew xistence$ PATH=/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cscope/bin:/usr/local/opt/python/bin:/usr/bin:/bin:/usr/sbin:/sbin python-config --prefix
/System/Library/Frameworks/Python.framework/Versions/2.7
```

Here's the binaries that are in the Python binpath:

```
Sterling:Homebrew xistence$ ls -lah /usr/local/opt/python/bin/
total 160
drwxr-xr-x  22 xistence  xistence   748B Jul 18 18:17 .
drwxr-xr-x  13 xistence  xistence   442B Jul 18 18:17 ..
lrwxr-xr-x   1 xistence  xistence    54B Dec 17  2016 2to3-2 -> ../Frameworks/Python.framework/Versions/2.7/bin/2to3-2
lrwxr-xr-x   1 xistence  xistence    56B Dec 17  2016 2to3-2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/2to3-2.7
-rwxr-xr-x   1 xistence  xistence   423B Jul 18 18:17 easy_install
-rwxr-xr-x   1 xistence  xistence   431B Jul 18 18:17 easy_install-2.7
lrwxr-xr-x   1 xistence  xistence    53B Dec 17  2016 idle2 -> ../Frameworks/Python.framework/Versions/2.7/bin/idle2
lrwxr-xr-x   1 xistence  xistence    55B Dec 17  2016 idle2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/idle2.7
-rwxr-xr-x   1 xistence  xistence   381B Jul 18 18:17 pip
-rwxr-xr-x   1 xistence  xistence   383B Jul 18 18:17 pip2
-rwxr-xr-x   1 xistence  xistence   387B Jul 18 18:17 pip2.7
lrwxr-xr-x   1 xistence  xistence    54B Dec 17  2016 pydoc2 -> ../Frameworks/Python.framework/Versions/2.7/bin/pydoc2
lrwxr-xr-x   1 xistence  xistence    56B Dec 17  2016 pydoc2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/pydoc2.7
lrwxr-xr-x   1 xistence  xistence    55B Dec 17  2016 python2 -> ../Frameworks/Python.framework/Versions/2.7/bin/python2
lrwxr-xr-x   1 xistence  xistence    62B Dec 17  2016 python2-config -> ../Frameworks/Python.framework/Versions/2.7/bin/python2-config
lrwxr-xr-x   1 xistence  xistence    57B Dec 17  2016 python2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x   1 xistence  xistence    64B Dec 17  2016 python2.7-config -> ../Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
lrwxr-xr-x   1 xistence  xistence    56B Dec 17  2016 pythonw2 -> ../Frameworks/Python.framework/Versions/2.7/bin/pythonw2
lrwxr-xr-x   1 xistence  xistence    58B Dec 17  2016 pythonw2.7 -> ../Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
lrwxr-xr-x   1 xistence  xistence    59B Dec 17  2016 smtpd2.7.py -> ../Frameworks/Python.framework/Versions/2.7/bin/smtpd2.7.py
lrwxr-xr-x   1 xistence  xistence    57B Dec 17  2016 smtpd2.py -> ../Frameworks/Python.framework/Versions/2.7/bin/smtpd2.py
-rwxr-xr-x   1 xistence  xistence   394B Jul 18 18:17 wheel
```

**Comment by bertjwregeer** [comment]
> Right, so macvim knows to look for python2, which is nice. Also, python and python2 will point to the same file, and python-config and python2-config will point to the same file, so I'm not seeing the problem yet.

`python-config` does not exist... so the brew Formula will call the wrong `python-config` because the only one left in the PATH is the MacOS system Python.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/commit/f08b5184816fdc99db8cd0dac1e4debbb2a8c14a

**Comment by ilovezfs** [comment]
@bertjwregeer I think that commit may not be working as expected.

**Comment by bertjwregeer** [comment]
@ilovezfs I would agree. Sadly my Ruby is not nearly strong enough to fix it.

**Comment by ilovezfs** [comment]
@bertjwregeer no worries. There should be a proper fix in the next day or so.

**Comment by ilovezfs** [comment]
For now the simplest workaround is probably
```
brew uninstall python
brew reinstall macvim --with-lua
brew install python
```

**Comment by bertjwregeer** [comment]
@ilovezfs: Posted that here: https://github.com/Homebrew/homebrew-core/issues/15741#issuecomment-316244019

**Comment by ilovezfs** [comment]
@bertjwregeer cool :)

**Comment by bertjwregeer** [comment]
You do need to make sure to compile from source, the poured keg is broken too...

**Comment by ilovezfs** [comment]
Still not sure why I cannot actually reproduce the breakage.

**Comment by wang-boyu** [comment]
Another workaround:

```bash
$ cd /Applications/MacVim.app/Contents/MacOS/
$ install_name_tool -change /System/Library/Frameworks/Python.framework/Versions/2.7/Python /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/Python Vim
```

**Comment by ilovezfs** [comment]
If any/some/all of you can test https://github.com/Homebrew/brew/pull/2917, that would be great.

**Comment by ilovezfs** [comment]
The bottles are now fix
```
iMac-TMP:~ joe$ brew install macvim
==> Downloading https://homebrew.bintray.com/bottles/macvim-8.0-134_2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring macvim-8.0-134_2.el_capitan.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/macvim/8.0-134_2: 2,133 files, 33.8MB
iMac-TMP:~ joe$ brew linkage macvim | grep -i py
  /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (python)
iMac-TMP:~ joe$
```

If you use Homebrew/brew's master, --build-from-source builds should be fixed, too.

**Comment by gatspy** [comment]
i have the same issue, which is caused by `ycm`,  i update `ycm` and `installed`, the problem still.

**Comment by pirminis** [comment]
@ilovezfs now a regular `brew update; brew upgrade` works as expected for _MacVim_

thank you very much ⭐️ 👍

**Comment by ilovezfs** [comment]
@pirminis you're welcome!

@gatspy please post `brew config`.
