### ISSUE TITLE
Cannot see rabbitmq running via services

### ISSUE THREAD

**Issue by morenoh149** [Homebrew/homebrew-core#17446]
I ran `brew services start rabbitmq` and `sudo brew services start rabbitmq`, neither of which make rabbitmq appear via `ps aux | grep rabbit`.
Running `brew services start rabbitmq` multiple times makes it say "Service _rabbitmq_ already started, use `brew services restart rabbitmq` to restart.".

How can I make launchd automatically start rabbitmq in the same way `sudo rabbitmq-server` does?
This would aid running celery ([Celery installation steps](http://docs.celeryproject.org/en/latest/getting-started/brokers/rabbitmq.html#starting-stopping-the-rabbitmq-server))

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# brew doctor output
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  <redacted>

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/pthread-barrier.h
  /usr/local/include/node/v8-experimental.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  node

Warning: Your Xcode (8.1) is outdated.
Please update to Xcode 8.3.3 (or delete it).
Xcode can be updated from the App Store.


Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/apm
  /usr/local/bin/atom

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install libpq lua

Run `brew missing` for more details.
```

# brew config
```
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8d7cf304e38a630c6beec10607ba938de250c0fe
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit nehalem
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.14.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.6-x86_64
Xcode: 8.1
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

# gist-logs
no logs

**Comment by dunn** [comment]
Sorry for the delay on this.  Can you try starting it in the same way it's specified in the plist, and see if it fails (and why)? https://github.com/Homebrew/homebrew-core/blob/master/Formula/rabbitmq.rb#L77-L87

Or if you see anything obviously wrong with that plist, we'd love a PR.

**Comment by simonemazzoni** [comment]
@dunn I have the same error. if i start rabbitmq with brew services it doesn't actually start, but I don't understand why. Could you reopen this issue?

**Comment by simonemazzoni** [comment]
UPDATE: I solved by emptying the `/usr/local/var/lib/rabbitmq` folder.

This seems to be related to the following line in the log error when try to start rabbit using the `rabbitmq-server` command without sudo in macosx.

```
{cannot_delete,
                   "/usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost-plugins-expand/amqp_client-3.7.2/ebin/amqp_auth_mechanisms.beam",
                   eacces}]}}

Don't know exactly why, but deleting all the files in that folder causes rabbit to recreate them and allows to run rabbit using `rabbitmq-server` command, and so start working also if started with the `brew services start/run rabbitmq` command.

**Comment by amardeepjabong** [comment]
Hi Im still facing this issue emptied  /usr/local/var/lib/rabbitmq too.

**Comment by simonemazzoni** [comment]
@amardeepjabong have you tried to, `brew uninstall rabbitmq`, clean the `/usr/local/var/lib/rabbitmq` folder, and `brew install rabbitmq`.
