### ISSUE TITLE
Xdot

### ISSUE THREAD

**Issue by tfchu** [Homebrew/homebrew-core#19187]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I need to use xdot and installed it (OS: Mac OS El Capitan v10.11.6)
```
$ brew install xdot
```

- What happened (include command output)
run 
```
$ xdot
```
error shows as follows
```
usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:39: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'document-print' for stock: Icon 'document-print' not present in theme Adwaita

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'zoom-in' for stock: Icon 'zoom-in' not present in theme Adwaita

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'zoom-out' for stock: Icon 'zoom-out' not present in theme Adwaita

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'zoom-fit-best' for stock: Icon 'zoom-fit-best' not present in theme Adwaita

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'zoom-original' for stock: Icon 'zoom-original' not present in theme Adwaita

(xdot:3302): Gtk-WARNING **: Error loading theme icon 'edit-find' for stock: Icon 'edit-find' not present in theme Adwaita

** (xdot:3302): WARNING **: Failed to load shared library 'libcairo-gobject.2.dylib' referenced by the typelib: dlopen(libcairo-gobject.2.dylib, 9): image not found
```

- What you expected to happen
xdot should run without a problem. Possible cause is brew installs .../python2.7/site-packages/xdot.py & xdot.pyc for python 2.7 but these two files are for python3 (see first line of xdot.py). I copied these two files for python2.7 from my ubuntu system and it fixed the issue. 

- Step-by-step reproduction instructions (by running `brew install` commands)
$ brew install xdot
$ xdot

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
Happy to review a PR fixing this.

**Comment by Qix-** [comment]
@ilovezfs why close this? Xdot doesn't even work at the moment, but the gtk theme "Adwaita" doesn't seem to have any stock icons, which is a larger issue IMO.

**Comment by ilovezfs** [comment]
@Qix- This should be fixed via https://github.com/Homebrew/homebrew-core/pull/25433 if you `brew upgrade xdot`

**Comment by derwentx** [comment]
I still have this problem with xdot 0.9_2 on macOS Sierra.
```

(xdot:18466): Gtk-WARNING **: 12:55:32.219: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:32.220: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:32.220: Error loading theme icon 'document-print' for stock: Icon 'document-print' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:32.220: Error loading theme icon 'zoom-in' for stock: Icon 'zoom-in' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:32.221: Error loading theme icon 'zoom-out' for stock: Icon 'zoom-out' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:32.221: Error loading theme icon 'zoom-fit-best' for stock: Icon 'zoom-fit-best' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:32.221: Error loading theme icon 'zoom-original' for stock: Icon 'zoom-original' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:32.221: Error loading theme icon 'edit-find' for stock: Icon 'edit-find' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:44.498: Error loading theme icon 'zoom-out' for stock: Icon 'zoom-out' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:44.516: Error loading theme icon 'zoom-out' for stock: Icon 'zoom-out' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:44.532: Error loading theme icon 'zoom-out' for stock: Icon 'zoom-out' not present in theme Adwaita

(xdot:18466): Gtk-WARNING **: 12:55:44.548: Error loading theme icon 'zoom-out' for stock: Icon 'zoom-out' not present in theme Adwaita
```
etc.

is it possible that homebrew is not installing stuff in the correct location because i use pyenv?

**Comment by ilovezfs** [comment]
Other than the warnings ... does xdot work?

**Comment by Qix-** [comment]
@ilovezfs Yes, but none of the icons work. It's extremely hard to tell what is what.
