### ISSUE TITLE
bazel: does not support Java 9, but formula specifies "java 1.8+"

### ISSUE THREAD

**Issue by parkr** [Homebrew/homebrew-core#20543]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

To help us debug your issue please explain:

### 1. What you were trying to do (and why)

I was trying to install & run bazel from `bazel.rb` formula.

### 2.  What happened (include command output)

I ran `brew install bazel`, which succeeded. Running `bazel` failed, however. `brew test bazel` also failed. Issue is filed on the `bazel` project: https://github.com/bazelbuild/bazel/issues/3410

```text
$ bazel
Problem with java installation: couldn't find/access rt.jar in /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
```

Gist logs: https://gist.github.com/parkr/af7b5098abebb8cd5c5fc89848c871f9

### 3.  What you expected to happen

I expected `bazel` to run. I expected Homebrew to install java 8 and link `bazel` to java 8 or tell me to set my `JAVA_HOME` to that bundled version of Java. I expected Homebrew to tell me it can't install bazel because I have an incompatible version of Java installed.

### 4. Step-by-step reproduction instructions (by running `brew install` commands)

1. `java --version` must show Java 9.
2. `brew install bazel`
3. `bazel` 💥 
4. `brew test bazel` 💥 

## Solution?

I'd propose **one of two solutions**:

1. Enforce in `bazel.rb` formula that Java must be version 8 or lower. This would prevent bazel from installing on machines with Java 9.
2. Install Java 8 in the user's Cellar and link `bazel` to that version of Java with a patch.

**Comment by ilovezfs** [comment]
Please file an issue upstream requesting Java 9 support. We may consider using a wrapper script in the meantime but that isn't a real solution.

**Comment by ilovezfs** [comment]
Ah I see you've pointed to https://github.com/bazelbuild/bazel/issues/3410. In any case I've added this to the list in https://github.com/Homebrew/homebrew-core/issues/20543.

**Comment by parkr** [comment]
@ilovezfs I believe amending the java requirements to “< 9” is an appropriate solution. Can you help me understand why this wouldn’t be ok?

**Comment by ilovezfs** [comment]
@parkr please test this: https://github.com/Homebrew/homebrew-core/pull/20544

**Comment by ilovezfs** [comment]
@parkr it should be fixed now if you `brew update` and `brew upgrade`

**Comment by haemi** [comment]
I still have the problem:
`brew doctor` => `Your system is ready to brew.`
`brew config` => `Java: 9`
`brew update` => `Already up-to-date.`

but `brew upgrade` gives:
```
bazel 0.7.0_1, imagemagick 7.0.7-11, protobuf 3.5.0
bazel: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
 brew cask install caskroom/versions/java8
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
```

**Comment by ilovezfs** [comment]
Yes, you still have the problem because the fix is to require and force the use of Java 8. So you need to install Java 8 as that message says.
