### ISSUE TITLE
Can not run gnuplot...

### ISSUE THREAD

**Issue by Yoshiyuki203** [Homebrew/homebrew-core#29221]
Hi,I installed gnuplot using homebrew.
$brew install gnuplot --with-aquaterm --with-x11
🍺  /usr/local/Cellar/gnuplot/5.2.4: 47 files, 2.7MB, built in 1 minute 2 seconds

This worked out fine, but ,If run gnuplot from the command line, I get the following output.

$ gnuplot
-bash: gnuplot: command not found

Homebrew version is 1.6.8.
I have Xcode 9.4.1 installed and I'm running 10.13.5 Mac OS High sierra.

$brew uninstall gnuplot
Uninstalling /usr/local/Cellar/gnuplot/5.2.4... (47 files, 2.7MB)
Maybe, No problem about uninstall.  

Please Help Me...

**Comment by amitkpal** [comment]
I have a similar problem. I am trying to install gnuplot in my Macbook. I have octave installed, and gnuplot comes with it. However, it is not showing any plot (can not set terminal). I have uninstalled gnuplot ($brew uninstall --ignore-dependencies gnuplot), and tried installing $brew install gnuplot --with-qt    which gives error message as follows.

Undefined symbols for architecture x86_64:
  "_gdImagePaletteToTrueColor", referenced from:
      _gdImageSixel in term.o
  "_gdImageTrueColorToPaletteSetMethod", referenced from:
      _gdImageSixel in term.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [gnuplot] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Can not run gnuplot... https://github.com/Homebrew/homebrew-core/issues/29221

Similar problem if I try to install gnuplot with x11. Please help.

**Comment by Yoshiyuki203** [comment]
My problem was solved.
uninstall gnuplot→uninstall homebrew→reinstall homebrew→install gnuplot

**Comment by amitkpal** [comment]
Thanks! However, uninstalling and re-installing homebrew did not solve my problem.

**Comment by mistydemeo** [comment]
@amitkpal Your error is not related. Can you please make sure you follow the instructions in the linked troubleshooting guide so that we have all of the relevant information we need to diagnose it? :)

**Comment by fxcoudert** [comment]
@amitkpal please open a new issue following bug reporting instructions there

**Comment by madamesophie** [comment]
Same problem here which was solved by  brew doctor  
and have noticed that gd was one of the unlinked kegs..
So 
brew link gd  
[or brew link --overwrite gd ]

then relaunch brew install gnuplot
