### ISSUE TITLE
gnutls failed to build on 10.12

### ISSUE THREAD

**Issue by AlexanderWillner** [Homebrew/homebrew-core#2938]
## General troubleshooting

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

## Bug report

* Gist: https://gist.github.com/anonymous/1222c7166f09c179a4581c270c2b8187
* Summary: Installing ```gnutls``` for ```openconnect``` on macOS 10.12 Beta (16A239m). I know, not supported yet. Just to track this issue for now.

**Comment by DomT4** [comment]
Can you `brew update` and try again? This may have been fixed via https://github.com/Homebrew/brew/commit/bd4e24ae8f6db6ad6f0020352b0b8a15cb1c21e2.

**Comment by DomT4** [comment]
If that doesn't work though, please do update your Xcode. Xcode 7 on 10.12 is an unsupported configuration with Apple, let alone us.

**Comment by AlexanderWillner** [comment]
Thanks for the reply. This didn't solve the issue. Latest gist: https://gist.github.com/bb32080737056ff1a5770f75505330f3

**Comment by rakkesh** [comment]
What do you get as output for `ls -l /usr/local/Cellar/nettle/3.2/lib/libhogweed*` and 
`pkg-config --libs hogweed`? Should be similar to the following -

```
$ ls -l /usr/local/Cellar/nettle/3.2/lib/libhogweed*
-r--r--r-- 1 rakkesh admin 191K Feb 11 14:59 libhogweed.4.2.dylib
lrwxr-xr-x 1 rakkesh admin   20 Feb  4 21:21 libhogweed.4.dylib -> libhogweed.4.2.dylib
-r--r--r-- 1 rakkesh admin 303K Jan 29 01:32 libhogweed.a
lrwxr-xr-x 1 rakkesh admin   20 Feb  4 21:21 libhogweed.dylib -> libhogweed.4.2.dylib
```
and 

``` 
$ pkg-config --libs hogweed
-L/usr/local/Cellar/nettle/3.2/lib -lhogweed
```

If not, try reinstalling `nettle`. Lastly, if it still doesn't work - upgrade CLT,
`$ xcode-select --install`.

**Comment by AlexanderWillner** [comment]
While ```nettle-3.2``` was already installed, the command ```brew reinstall nettle``` did the trick (now with Xcode 8.0 installed). Now I ran into #2991.
