### ISSUE TITLE
Agda failed to build on 10.10

### ISSUE THREAD

**Issue by madgen** [Homebrew/homebrew-core#3168]
- [x] Ran `brew update` and retried your prior step?

Also tried upgrading everything.
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Yup, it reports no issues.
### Bug report:

Agda fails to install from source on Yosemite (10.10) ie. `brew install -s agda`. It succeeds using bottles.

Note that it also fails if I do "--without-stdlib".

`brew gist-logs agda`

https://gist.github.com/anonymous/a0e86b5ea77f0bda8ee0059e61ead793

When I run it for a second time (right after it failed without changing anything else), it fails with a different error. Here are the logs for that:

https://gist.github.com/anonymous/94f3376530e8e2631ff354c10d4a7d2c

**Comment by ilovezfs** [comment]
Neat. I'll take a look.

**Comment by ilovezfs** [comment]
@madgen  The error is
```
[20 of 24] Compiling Language.Haskell.Exts.InternalParser ( dist/dist-sandbox-a9dc4f2d/build/Language/Haskell/Exts/InternalParser.hs, dist/dist-sandbox-a9dc4f2d/build/Language/Haskell/Exts/InternalParser.o )
dist/dist-sandbox-a9dc4f2d/build/Language/Haskell/Exts/InternalParser.o: getModificationTime: does not exist (No such file or directory)
cabal: Leaving directory '/var/folders/k3/2mjf5njs0_36dhrx60rzqcfr0000gn/T/cabal-tmp-21283/haskell-src-exts-1.17.1'
Failed to install haskell-src-exts-1.17.1
cabal: Error: some packages failed to install:
haskell-src-exts-1.17.1 failed during the building phase. The exception was:
ExitFailure 1
```

Since I cannot reproduce build failure for haskell-src-exts, I think this may be a transient timing issue. Do you mind trying the build again?

**Comment by ilovezfs** [comment]
@madgen actually that second build was successful. Your emacs is just too old.
```
brew install emacs
```
before doing the agda installation.

**Comment by ilovezfs** [comment]
@DomT4 obviously this one should have a minimum emacs requirement as discussed here https://github.com/agda/agda/issues/1945#issuecomment-212995311

**Comment by DomT4** [comment]
@ilovezfs If you can find out roughly which version it needs, feel free to tack that into the formula 👍.

**Comment by madgen** [comment]
@ilovezfs No, problem at all. To save time I have built without the stdlib, but the error is similar.

Here's the new gist:
https://gist.github.com/anonymous/b63916383ac06fa5588f65b1462e214d

I am running it for the second time (having updated emacs) now to see if it builds on second try. I will let you know if/when it finishes.

**Comment by madgen** [comment]
@ilovezfs _the second attempt_ after updating emacs installed correctly.

@DomT4 emacs 24.5 makes it work, but I don't think it is a tight enough bound. 😄

**Comment by DomT4** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-core/commit/e83c8271c95e743290461ecfc4d330e0c5716b33.

**Comment by madgen** [comment]
@DomT4: No, the first installation still fails before it reaches the emacs requirements see the first gist, and the other one submitted per @ilovezfs's request.

**Comment by ilovezfs** [comment]
@madgen yeah we can poke more at that haskell-src-exts issue if you'd like

**Comment by DomT4** [comment]
Whoops. @ilovezfs Feel free to reopen if you'd like.

**Comment by madgen** [comment]
@ilovezfs That would be great!

**Comment by ilovezfs** [comment]
@madgen If you're still curious about this issue, the current version of haskell-src-exts is now 1.19.0, which was released 4 days ago. If you can still reproduce the problem, it would be good to let agda upstream know, since they're still pinning the haskell-src-exts version at < 1.18 https://github.com/agda/agda/blob/master/Agda.cabal#L155 but the issue may already have been fixed in one of the newer versions (1.18.0, 1.18.1, 1.18.2, 1.19.0).
