### ISSUE TITLE
clamav does not link to system libxml2 on Sierra

### ISSUE THREAD

**Issue by taw123** [Homebrew/homebrew-core#32690]
**Issue:** Installation of via Brew of ClamAV version v 0.100.1 (and actually it seems ANY version greater then 0.99.2) on Mac OS X 10.12.6 DOES NOT scan DMG’s and FALSELY reports no infected files. If that same image is mounted locally and the MOUNTED directly scanned the eicar test file is appropriately flagged.

So the questions First HOW to enable libxml2 support when in Brew install, IF it is AS CLAIMED a required to support DMG scanning. Second WHY is this not enabled by default as this creates a HUGE security whole, with users expecting DMG support per ClamAV documentation, but Brew building strips out this support.  

**Postulated Cause:** Missing DMG support tracked back to libxml2  Per debug test of run of clamscan run against a test DMG that contains eicar.com.zip it seems that Brew is installing a version of ClamAV with DMG support DISABLED because it has compiled out support for libxml2 which ClamAV claims is required for DMG support. (Supporting details below and in diagnostics listing of the debug log at the bottom)
`LibClamAV debug: cli_scandmg: libxml2 support is compiled out`. It is required for full DMG support.  

**Attempts to resolve/diagnose/confirm supposition:**
1. Confirmed `libxml2` IS LOCALLY INSTALLED (version 2.9.4 likely via CLT)
2. Confirm that Brew’d ClamAV Version 0.99.2 that DOES correctly scan DMGs DID have `libxml2` support enabled per  `clamconf` report (excerpted below).
    - Version:0.99.2
                `Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE RAR`
    - Version: 0.100.1
                `Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 PCRE RAR`

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? - [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
   ```  
           brew gist-logs clamav
           Error: No logs.```
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f5882f8610762f33c12e0acd72c3a6a2030deaf
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MACOS_VERSION_NUMERIC: 101206
HOMEBREW_NO_ANALYTICS: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11, 10.0.1, 10, 9.0.4
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A
```


### **Supporting Diagnostic info:**
* Installed version of  `libxml2` is 2.9.4 (via CLT I believe)
```
xmllint --version
xmllint: using libxml version 20904
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib 

```

```
grep -Ri "LIBXML_DOTTED_VERSION" /usr/include/libxml2/libxml/xmlversion.h
/usr/include/libxml2/libxml/xmlversion.h: * LIBXML_DOTTED_VERSION:
/usr/include/libxml2/libxml/xmlversion.h:#define LIBXML_DOTTED_VERSION "2.9.4"

```

* Brew config
```
brew --config
HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f5882f8610762f33c12e0acd72c3a6a2030deaf
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MACOS_VERSION_NUMERIC: 101206
HOMEBREW_NO_ANALYTICS: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11, 10.0.1, 10, 9.0.4
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A
```


* Formulas used to install ClamAV via Brew
    * v.100.1
        * https://github.com/Homebrew/homebrew-core/blob/master/Formula/clamav.rb
    * v.99.2
        * https://raw.githubusercontent.com/Homebrew/homebrew-core/03e1b27b9b6925995d07c6e48833bbfe8f871408/Formula/clamav.rb


* ClamConf report for Version: 0.99.2
```
Last login: Mon Oct  1 21:51:52 on ttys017
Desktop-Air:~ weyer_l$ clamconf
Checking configuration files in /usr/local/etc/clamav
Config file: clamd.conf
-----------------------
LogFile = "/Library/Logs/ClamAV/clamd.log"
StatsHostID disabled
StatsEnabled disabled
StatsPEDisabled disabled
StatsTimeout disabled
LogFileUnlock disabled
LogFileMaxSize = "2097152"
LogTime = "yes"
LogClean disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
PidFile disabled
TemporaryDirectory disabled
DatabaseDirectory = "/usr/local/share/clamav"
OfficialDatabaseOnly disabled
LocalSocket = "/usr/local/var/run/clamav/clamd.sock"
LocalSocketGroup disabled
LocalSocketMode disabled
FixStaleSocket = "yes"
TCPSocket disabled
TCPAddr disabled
MaxConnectionQueueLength = "200"
StreamMaxLength = "26214400"
StreamMinPort = "1024"
StreamMaxPort = "2048"
MaxThreads = "10"
ReadTimeout = "120"
CommandReadTimeout = "5"
SendBufTimeout = "500"
MaxQueue = "100"
IdleTimeout = "30"
ExcludePath disabled
MaxDirectoryRecursion = "15"
FollowDirectorySymlinks disabled
FollowFileSymlinks disabled
CrossFilesystems = "yes"
SelfCheck = "600"
DisableCache disabled
VirusEvent = "osascript -e "beep 2" && open -a /usr/local/bin/terminal-notifier --args -title "ClamD Scan" -subtitle "Infection detected" -message "%v"  >/dev/null"
ExitOnOOM = "yes"
AllowAllMatchScan = "yes"
Foreground disabled
Debug disabled
LeaveTemporaryFiles disabled
User disabled
AllowSupplementaryGroups disabled
Bytecode = "yes"
BytecodeSecurity = "TrustSigned"
BytecodeTimeout = "5000"
BytecodeUnsigned disabled
BytecodeMode = "Auto"
DetectPUA disabled
ExcludePUA disabled
IncludePUA disabled
AlgorithmicDetection = "yes"
ScanPE = "yes"
ScanELF = "yes"
DetectBrokenExecutables disabled
ScanMail = "yes"
ScanPartialMessages disabled
PhishingSignatures = "yes"
PhishingScanURLs = "yes"
PhishingAlwaysBlockCloak disabled
PhishingAlwaysBlockSSLMismatch disabled
PartitionIntersection disabled
HeuristicScanPrecedence disabled
StructuredDataDetection disabled
StructuredMinCreditCardCount = "3"
StructuredMinSSNCount = "3"
StructuredSSNFormatNormal = "yes"
StructuredSSNFormatStripped disabled
ScanHTML = "yes"
ScanOLE2 = "yes"
OLE2BlockMacros disabled
ScanPDF = "yes"
ScanSWF = "yes"
ScanXMLDOCS = "yes"
ScanHWP3 = "yes"
ScanArchive = "yes"
ArchiveBlockEncrypted disabled
ForceToDisk disabled
MaxScanSize = "3145728000"
MaxFileSize = "3145728000"
MaxRecursion = "16"
MaxFiles = "10000"
MaxEmbeddedPE = "10485760"
MaxHTMLNormalize = "10485760"
MaxHTMLNoTags = "2097152"
MaxScriptNormalize = "5242880"
MaxZipTypeRcg = "1048576"
MaxPartitions = "50"
MaxIconsPE = "100"
MaxRecHWP3 = "16"
PCREMatchLimit = "10000"
PCRERecMatchLimit = "5000"
PCREMaxFileSize = "26214400"
ScanOnAccess disabled
OnAccessMountPath disabled
OnAccessIncludePath disabled
OnAccessExcludePath disabled
OnAccessExcludeUID disabled
OnAccessMaxFileSize = "5242880"
OnAccessDisableDDD disabled
OnAccessPrevention disabled
OnAccessExtraScanning disabled
DevACOnly disabled
DevACDepth disabled
DevPerformance disabled
DevLiblog disabled
DisableCertCheck disabled
Config file: freshclam.conf
---------------------------
StatsHostID disabled
StatsEnabled disabled
StatsTimeout disabled
LogFileMaxSize = "2097152"
LogTime = "yes"
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose = "yes"
LogRotate = "yes"
PidFile disabled
DatabaseDirectory = "/usr/local/share/clamav"
Foreground disabled
Debug disabled
AllowSupplementaryGroups disabled
UpdateLogFile = "/Library/Logs/ClamAV/freshclam.log"
DatabaseOwner = "_clamav"
Checks = "12"
DNSDatabaseInfo = "current.cvd.clamav.net"
DatabaseMirror = "db.US.big.clamav.net", "database.clamav.net"
PrivateMirror disabled
MaxAttempts = "3"
ScriptedUpdates = "yes"
TestDatabases = "yes"
CompressLocalDatabase disabled
ExtraDatabase disabled
DatabaseCustomURL disabled
HTTPProxyServer disabled
HTTPProxyPort disabled
HTTPProxyUsername disabled
HTTPProxyPassword disabled
HTTPUserAgent disabled
NotifyClamd = "/usr/local/etc/clamav/clamd.conf"
OnUpdateExecute disabled
OnErrorExecute disabled
OnOutdatedExecute disabled
LocalIPAddress disabled
ConnectTimeout = "30"
ReceiveTimeout = "30"
SubmitDetectionStats disabled
DetectionStatsCountry disabled
DetectionStatsHostID disabled
SafeBrowsing disabled
Bytecode = "yes"
clamav-milter.conf not found
Software settings
-----------------
Version: 0.99.2
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE RAR
Database information
--------------------
Database directory: /usr/local/share/clamav
bytecode.cld: version 327, sigs: 91, built on Wed Aug  8 17:43:48 2018
daily.cld: version 24998, sigs: 2103387, built on Mon Oct  1 01:58:25 2018
main.cvd: version 58, sigs: 4566249, built on Wed Jun  7 14:38:10 2017
Total number of signatures: 6669727
Platform information
--------------------
uname: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root x86_64
OS: darwin16.0.0, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.8 (1.2.8), compile flags: a9
platform id: 0x042352520800000000040201
Build information
-----------------
Clang: 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38) (4.2.1)
CPPFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include
CFLAGS: -g -O2  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
CXXFLAGS:
LDFLAGS:
Configure: '--disable-dependency-tracking' '--disable-silent-rules' '--prefix=/usr/local/Cellar/clamav/0.99.2_1' '--libdir=/usr/local/Cellar/clamav/0.99.2_1/lib' '--sysconfdir=/usr/local/etc/clamav' '--disable-zlib-vcheck' '--with-zlib=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr' '--with-openssl=/usr/local/opt/openssl' '--enable-llvm=no' '--with-pcre=/usr/local/opt/pcre' '--disable-yara' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.12' --enable-ltdl-convenience
sizeof(void*) = 8
Engine flevel: 82, dconf: 82
Desktop-Air:~ weyer_l$ clamconf
Checking configuration files in /usr/local/etc/clamav
Config file: clamd.conf
-----------------------
LogFile = "/Library/Logs/ClamAV/clamd.log"
StatsHostID disabled
StatsEnabled disabled
StatsPEDisabled disabled
StatsTimeout disabled
LogFileUnlock disabled
LogFileMaxSize = "2097152"
LogTime = "yes"
LogClean disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
PidFile disabled
TemporaryDirectory disabled
DatabaseDirectory = "/usr/local/share/clamav"
OfficialDatabaseOnly disabled
LocalSocket = "/usr/local/var/run/clamav/clamd.sock"
LocalSocketGroup disabled
LocalSocketMode disabled
FixStaleSocket = "yes"
TCPSocket disabled
TCPAddr disabled
MaxConnectionQueueLength = "200"
StreamMaxLength = "26214400"
StreamMinPort = "1024"
StreamMaxPort = "2048"
MaxThreads = "10"
ReadTimeout = "120"
CommandReadTimeout = "5"
SendBufTimeout = "500"
MaxQueue = "100"
IdleTimeout = "30"
ExcludePath disabled
MaxDirectoryRecursion = "15"
FollowDirectorySymlinks disabled
FollowFileSymlinks disabled
CrossFilesystems = "yes"
SelfCheck = "600"
DisableCache disabled
VirusEvent = "osascript -e "beep 2" && /usr/local/bin/terminal-notifier --args -title "ClamD Scan" -subtitle "Infection detected" -message "%v"  >/dev/null"
ExitOnOOM = "yes"
AllowAllMatchScan = "yes"
Foreground disabled
Debug disabled
LeaveTemporaryFiles disabled
User disabled
AllowSupplementaryGroups disabled
Bytecode = "yes"
BytecodeSecurity = "TrustSigned"
BytecodeTimeout = "5000"
BytecodeUnsigned disabled
BytecodeMode = "Auto"
DetectPUA disabled
ExcludePUA disabled
IncludePUA disabled
AlgorithmicDetection = "yes"
ScanPE = "yes"
ScanELF = "yes"
DetectBrokenExecutables disabled
ScanMail = "yes"
ScanPartialMessages disabled
PhishingSignatures = "yes"
PhishingScanURLs = "yes"
PhishingAlwaysBlockCloak disabled
PhishingAlwaysBlockSSLMismatch disabled
PartitionIntersection disabled
HeuristicScanPrecedence disabled
StructuredDataDetection disabled
StructuredMinCreditCardCount = "3"
StructuredMinSSNCount = "3"
StructuredSSNFormatNormal = "yes"
StructuredSSNFormatStripped disabled
ScanHTML = "yes"
ScanOLE2 = "yes"
OLE2BlockMacros disabled
ScanPDF = "yes"
ScanSWF = "yes"
ScanXMLDOCS = "yes"
ScanHWP3 = "yes"
ScanArchive = "yes"
ArchiveBlockEncrypted disabled
ForceToDisk disabled
MaxScanSize = "3145728000"
MaxFileSize = "3145728000"
MaxRecursion = "16"
MaxFiles = "10000"
MaxEmbeddedPE = "10485760"
MaxHTMLNormalize = "10485760"
MaxHTMLNoTags = "2097152"
MaxScriptNormalize = "5242880"
MaxZipTypeRcg = "1048576"
MaxPartitions = "50"
MaxIconsPE = "100"
MaxRecHWP3 = "16"
PCREMatchLimit = "10000"
PCRERecMatchLimit = "5000"
PCREMaxFileSize = "26214400"
ScanOnAccess disabled
OnAccessMountPath disabled
OnAccessIncludePath disabled
OnAccessExcludePath disabled
OnAccessExcludeUID disabled
OnAccessMaxFileSize = "5242880"
OnAccessDisableDDD disabled
OnAccessPrevention disabled
OnAccessExtraScanning disabled
DevACOnly disabled
DevACDepth disabled
DevPerformance disabled
DevLiblog disabled
DisableCertCheck disabled
Config file: freshclam.conf
---------------------------
StatsHostID disabled
StatsEnabled disabled
StatsTimeout disabled
LogFileMaxSize = "2097152"
LogTime = "yes"
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose = "yes"
LogRotate = "yes"
PidFile disabled
DatabaseDirectory = "/usr/local/share/clamav"
Foreground disabled
Debug disabled
AllowSupplementaryGroups disabled
UpdateLogFile = "/Library/Logs/ClamAV/freshclam.log"
DatabaseOwner = "_clamav"
Checks = "12"
DNSDatabaseInfo = "current.cvd.clamav.net"
DatabaseMirror = "db.US.big.clamav.net", "database.clamav.net"
PrivateMirror disabled
MaxAttempts = "3"
ScriptedUpdates = "yes"
TestDatabases = "yes"
CompressLocalDatabase disabled
ExtraDatabase disabled
DatabaseCustomURL disabled
HTTPProxyServer disabled
HTTPProxyPort disabled
HTTPProxyUsername disabled
HTTPProxyPassword disabled
HTTPUserAgent disabled
NotifyClamd = "/usr/local/etc/clamav/clamd.conf"
OnUpdateExecute disabled
OnErrorExecute disabled
OnOutdatedExecute disabled
LocalIPAddress disabled
ConnectTimeout = "30"
ReceiveTimeout = "30"
SubmitDetectionStats disabled
DetectionStatsCountry disabled
DetectionStatsHostID disabled
SafeBrowsing disabled
Bytecode = "yes"
clamav-milter.conf not found
Software settings
-----------------
Version: 0.99.2
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE RAR
Database information
--------------------
Database directory: /usr/local/share/clamav
bytecode.cld: version 327, sigs: 91, built on Wed Aug  8 17:43:48 2018
daily.cld: version 24998, sigs: 2103387, built on Mon Oct  1 01:58:25 2018
main.cvd: version 58, sigs: 4566249, built on Wed Jun  7 14:38:10 2017
Total number of signatures: 6669727
Platform information
--------------------
uname: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root x86_64
OS: darwin16.0.0, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.8 (1.2.8), compile flags: a9
platform id: 0x042352520800000000040201
Build information
-----------------
Clang: 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38) (4.2.1)
CPPFLAGS: -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include
CFLAGS: -g -O2  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
CXXFLAGS:
LDFLAGS:
Configure: '--disable-dependency-tracking' '--disable-silent-rules' '--prefix=/usr/local/Cellar/clamav/0.99.2_1' '--libdir=/usr/local/Cellar/clamav/0.99.2_1/lib' '--sysconfdir=/usr/local/etc/clamav' '--disable-zlib-vcheck' '--with-zlib=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr' '--with-openssl=/usr/local/opt/openssl' '--enable-llvm=no' '--with-pcre=/usr/local/opt/pcre' '--disable-yara' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.12' --enable-ltdl-convenience
sizeof(void*) = 8
Engine flevel: 82, dconf: 82
```

* ClamConf report for Version: 0.100.1
```
Desktop-Air:~ weyer_l$ clamconf
Checking configuration files in /usr/local/etc/clamav
Config file: clamd.conf
-----------------------
BlockMax disabled
PreludeEnable disabled
PreludeAnalyzerName disabled
LogFile = "/Library/Logs/ClamAV/clamd.log"
LogFileUnlock disabled
LogFileMaxSize = "2097152"
LogTime = "yes"
LogClean disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
PidFile disabled
TemporaryDirectory disabled
DatabaseDirectory = "/usr/local/share/clamav"
OfficialDatabaseOnly disabled
LocalSocket = "/usr/local/var/run/clamav/clamd.sock"
LocalSocketGroup disabled
LocalSocketMode disabled
FixStaleSocket = "yes"
TCPSocket disabled
TCPAddr disabled
MaxConnectionQueueLength = "200"
StreamMaxLength = "26214400"
StreamMinPort = "1024"
StreamMaxPort = "2048"
MaxThreads = "10"
ReadTimeout = "120"
CommandReadTimeout = "5"
SendBufTimeout = "500"
MaxQueue = "100"
IdleTimeout = "30"
ExcludePath disabled
MaxDirectoryRecursion = "15"
FollowDirectorySymlinks disabled
FollowFileSymlinks disabled
CrossFilesystems = "yes"
SelfCheck = "600"
DisableCache disabled
VirusEvent = "osascript -e "beep 2" && /usr/local/bin/terminal-notifier --args -title "ClamD Scan" -subtitle "Infection detected" -message "%v"  >/dev/null"
ExitOnOOM = "yes"
AllowAllMatchScan = "yes"
Foreground disabled
Debug disabled
LeaveTemporaryFiles disabled
User disabled
Bytecode = "yes"
BytecodeSecurity = "TrustSigned"
BytecodeTimeout = "5000"
BytecodeUnsigned disabled
BytecodeMode = "Auto"
DetectPUA disabled
ExcludePUA disabled
IncludePUA disabled
AlgorithmicDetection = "yes"
ScanPE = "yes"
ScanELF = "yes"
DetectBrokenExecutables disabled
ScanMail = "yes"
ScanPartialMessages disabled
PhishingSignatures = "yes"
PhishingScanURLs = "yes"
PhishingAlwaysBlockCloak disabled
PhishingAlwaysBlockSSLMismatch disabled
PartitionIntersection disabled
HeuristicScanPrecedence disabled
StructuredDataDetection disabled
StructuredMinCreditCardCount = "3"
StructuredMinSSNCount = "3"
StructuredSSNFormatNormal = "yes"
StructuredSSNFormatStripped disabled
ScanHTML = "yes"
ScanOLE2 = "yes"
OLE2BlockMacros disabled
ScanPDF = "yes"
ScanSWF = "yes"
ScanXMLDOCS = "yes"
ScanHWP3 = "yes"
ScanArchive = "yes"
ArchiveBlockEncrypted disabled
ForceToDisk disabled
MaxScanSize = "3145728000"
MaxFileSize = "3145728000"
MaxRecursion = "16"
MaxFiles = "10000"
MaxEmbeddedPE = "10485760"
MaxHTMLNormalize = "10485760"
MaxHTMLNoTags = "2097152"
MaxScriptNormalize = "5242880"
MaxZipTypeRcg = "1048576"
MaxPartitions = "50"
MaxIconsPE = "100"
MaxRecHWP3 = "16"
PCREMatchLimit = "100000"
PCRERecMatchLimit = "5000"
PCREMaxFileSize = "26214400"
ScanOnAccess disabled
OnAccessMountPath disabled
OnAccessIncludePath disabled
OnAccessExcludePath disabled
OnAccessExcludeRootUID disabled
OnAccessExcludeUID disabled
OnAccessMaxFileSize = "5242880"
OnAccessDisableDDD disabled
OnAccessPrevention disabled
OnAccessExtraScanning disabled
DevACOnly disabled
DevACDepth disabled
DevPerformance disabled
DevLiblog disabled
DisableCertCheck disabled
Config file: freshclam.conf
---------------------------
LogFileMaxSize = "2097152"
LogTime = "yes"
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose = "yes"
LogRotate = "yes"
PidFile disabled
DatabaseDirectory = "/usr/local/share/clamav"
Foreground disabled
Debug disabled
UpdateLogFile = "/Library/Logs/ClamAV/freshclam.log"
DatabaseOwner = "_clamav"
Checks = "12"
DNSDatabaseInfo = "current.cvd.clamav.net"
DatabaseMirror = "db.US.big.clamav.net", "database.clamav.net"
PrivateMirror disabled
MaxAttempts = "3"
ScriptedUpdates = "yes"
TestDatabases = "yes"
CompressLocalDatabase disabled
ExtraDatabase disabled
DatabaseCustomURL disabled
HTTPProxyServer disabled
HTTPProxyPort disabled
HTTPProxyUsername disabled
HTTPProxyPassword disabled
HTTPUserAgent disabled
NotifyClamd = "/usr/local/etc/clamav/clamd.conf"
OnUpdateExecute disabled
OnErrorExecute disabled
OnOutdatedExecute disabled
LocalIPAddress disabled
ConnectTimeout = "30"
ReceiveTimeout = "30"
SafeBrowsing disabled
Bytecode = "yes"
clamav-milter.conf not found
Software settings
-----------------
Version: 0.100.1
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 PCRE RAR
Database information
--------------------
Database directory: /usr/local/share/clamav
bytecode.cvd: version 327, sigs: 91, built on Wed Aug  8 17:43:48 2018
daily.cvd: version 25003, sigs: 2108076, built on Wed Oct  3 05:47:04 2018
main.cvd: version 58, sigs: 4566249, built on Wed Jun  7 14:38:10 2017
Total number of signatures: 6674416
Platform information
--------------------
uname: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root x86_64
OS: darwin16.7.0, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.8 (1.2.8), compile flags: a9
platform id: 0x04235c5c0800000000040201
Build information
-----------------
Clang: 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2) (4.2.1)
CPPFLAGS:
CFLAGS: -g -O2  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS:
LDFLAGS:
Configure: '--disable-dependency-tracking' '--disable-silent-rules' '--prefix=/usr/local/Cellar/clamav/0.100.1' '--libdir=/usr/local/Cellar/clamav/0.100.1/lib' '--sysconfdir=/usr/local/etc/clamav' '--with-openssl=/usr/local/opt/openssl' '--with-pcre=/usr/local/opt/pcre' '--disable-zlib-vcheck' '--enable-llvm=no' '--without-libjson' '--disable-yara' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12' --enable-ltdl-convenience
sizeof(void*) = 8
Engine flevel: 92, dconf: 92
```

*  Debug run failing to scan DMG [clamscan -r --debug /Users/weyer_l/Downloads/----Known\ virus\ for\ testing/Known\ Virus\]
```
clamscan -r --debug /Users/weyer_l/Downloads/----Known\ virus\ for\ testing/Known\ Virus\

<…>

LibClamAV debug: Building regex list
LibClamAV debug: Using filter for trie 0
LibClamAV debug: hashtab: Freeing hashset, elements: 0, capacity: 0
LibClamAV debug: Building regex list
LibClamAV debug: Using filter for trie 0
LibClamAV debug: hashtab: Freeing hashset, elements: 0, capacity: 0
LibClamAV debug: Dynamic engine configuration settings:
LibClamAV debug: --------------------------------------
LibClamAV debug: Module PE: On
LibClamAV debug:    * Submodule     PARITE: On
LibClamAV debug:    * Submodule       KRIZ: On
LibClamAV debug:    * Submodule    MAGISTR: On
LibClamAV debug:    * Submodule    POLIPOS: On
LibClamAV debug:    * Submodule    MD5SECT: On
LibClamAV debug:    * Submodule        UPX: On
LibClamAV debug:    * Submodule        FSG: On
LibClamAV debug:    * Submodule    SWIZZOR: ** Off **
LibClamAV debug:    * Submodule     PETITE: On
LibClamAV debug:    * Submodule     PESPIN: On
LibClamAV debug:    * Submodule         YC: On
LibClamAV debug:    * Submodule     WWPACK: On
LibClamAV debug:    * Submodule     NSPACK: On
LibClamAV debug:    * Submodule        MEW: On
LibClamAV debug:    * Submodule      UPACK: On
LibClamAV debug:    * Submodule     ASPACK: On
LibClamAV debug:    * Submodule    CATALOG: On
LibClamAV debug:    * Submodule      CERTS: On
LibClamAV debug:    * Submodule  MATCHICON: On
LibClamAV debug:    * Submodule     IMPTBL: On
LibClamAV debug: Module ELF: On
LibClamAV debug: Module MACHO: On
LibClamAV debug: Module ARCHIVE: On
LibClamAV debug:    * Submodule        RAR: On
LibClamAV debug:    * Submodule        ZIP: On
LibClamAV debug:    * Submodule       GZIP: On
LibClamAV debug:    * Submodule       BZIP: On
LibClamAV debug:    * Submodule        ARJ: On
LibClamAV debug:    * Submodule       SZDD: On
LibClamAV debug:    * Submodule        CAB: On
LibClamAV debug:    * Submodule        CHM: On
LibClamAV debug:    * Submodule       OLE2: On
LibClamAV debug:    * Submodule        TAR: On
LibClamAV debug:    * Submodule       CPIO: On
LibClamAV debug:    * Submodule     BINHEX: On
LibClamAV debug:    * Submodule        SIS: On
LibClamAV debug:    * Submodule       NSIS: On
LibClamAV debug:    * Submodule     AUTOIT: On
LibClamAV debug:    * Submodule    ISHIELD: On
LibClamAV debug:    * Submodule       7zip: On
LibClamAV debug:    * Submodule    ISO9660: On
LibClamAV debug:    * Submodule        DMG: On
LibClamAV debug:    * Submodule        XAR: On
LibClamAV debug:    * Submodule    HFSPLUS: On
LibClamAV debug:    * Submodule         XZ: On
LibClamAV debug:    * Submodule     PASSWD: On
LibClamAV debug:    * Submodule        MBR: On
LibClamAV debug:    * Submodule        GPT: On
LibClamAV debug:    * Submodule        APM: On
LibClamAV debug: Module DOCUMENT: On
LibClamAV debug:    * Submodule       HTML: On
LibClamAV debug:    * Submodule        RTF: On
LibClamAV debug:    * Submodule        PDF: On
LibClamAV debug:    * Submodule     SCRIPT: On
LibClamAV debug:    * Submodule HTMLSKIPRAW: On
LibClamAV debug:    * Submodule     JSNORM: On
LibClamAV debug:    * Submodule        SWF: On
LibClamAV debug:    * Submodule      OOXML: On
LibClamAV debug:    * Submodule      MSPML: On
LibClamAV debug:    * Submodule        HWP: On
LibClamAV debug: Module MAIL: On
LibClamAV debug:    * Submodule       MBOX: On
LibClamAV debug:    * Submodule       TNEF: On
LibClamAV debug: Module OTHER: On
LibClamAV debug:    * Submodule  UUENCODED: On
LibClamAV debug:    * Submodule     SCRENC: On
LibClamAV debug:    * Submodule       RIFF: On
LibClamAV debug:    * Submodule       JPEG: On
LibClamAV debug:    * Submodule    CRYPTFF: On
LibClamAV debug:    * Submodule        DLP: On
LibClamAV debug:    * Submodule  MYDOOMLOG: On
LibClamAV debug:    * Submodule PREFILTERING: On
LibClamAV debug:    * Submodule PDFNAMEOBJ: On
LibClamAV debug:    * Submodule  PRTNINTXN: On
LibClamAV debug:    * Submodule        LZW: On
LibClamAV debug: Module PHISHING On
LibClamAV debug:    * Submodule     ENGINE: On
LibClamAV debug:    * Submodule    ENTCONV: On
LibClamAV debug: Module BYTECODE On
LibClamAV debug:    * Submodule INTERPRETER: On
LibClamAV debug:    * Submodule    JIT X86: On
LibClamAV debug:    * Submodule    JIT PPC: On
LibClamAV debug:    * Submodule    JIT ARM: ** Off **
LibClamAV debug: Module STATS Off
LibClamAV debug: Module PCRE On
LibClamAV debug:    * Submodule    SUPPORT: On
LibClamAV debug:    * Submodule    OPTIONS: On
LibClamAV debug:    * Submodule     GLOBAL: On
LibClamAV debug: pool memory used: 578.683 MB
LibClamAV debug: environment detected:
LibClamAV debug: check_platform(0x04235c5c, 0x08000000, 0x00040201)
LibClamAV debug: check_platform(0x04  2  3  5c  5c,0x0  8       00 00 00,0x00    04 02 01)
LibClamAV debug: check_platform( OS CPU COM FL DCONF,BE PTR CXX VV.VV.VV, FLG CC VV.VV.VV)
LibClamAV debug: Engine version: 0.100.1
LibClamAV debug: Host triple:
LibClamAV debug: Host CPU:
LibClamAV debug: OS: Darwin
LibClamAV debug: OS release: 16.7.0
LibClamAV debug: OS version: Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root
LibClamAV debug: OS hardware: x86_64
LibClamAV debug: OS LLVM category: 0
LibClamAV debug: Has JIT compiled: 0
LibClamAV debug: ------------------------------------------------------
LibClamAV debug: Bytecode: mode is 0
LibClamAV debug: Loading trusted bytecode
LibClamAV debug: bytecode: Parsed 9 APIcalls, maxapi 74
LibClamAV debug: unknown inst type: 96
LibClamAV debug: unknown inst type: 67
LibClamAV debug: unknown inst type: 67
LibClamAV debug: unknown inst type: 67
LibClamAV debug: unknown inst type: 67
LibClamAV debug: unknown inst type: 67
LibClamAV debug: unknown inst type: 67
LibClamAV debug: unknown inst type: 67
LibClamAV debug: unknown inst type: 67
LibClamAV debug: Parsed 53 BBs, 226 instructions
LibClamAV debug: Parsed 1 functions
LibClamAV debug: Bytecode: BC_STARTUP running (builtin)
LibClamAV debug: Bytecode 0: executing in interpreter mode
LibClamAV debug: bytecode: registered ctx variable at 0x1100f4100 (+256) id 6
LibClamAV debug: bytecode: registered ctx variable at 0x1100f3ff4 (+2) id 2
LibClamAV debug: bytecode: registered ctx variable at 0x1100f4000 (+256) id 1
LibClamAV debug: bytecode: registered ctx variable at 0x1100f4200 (+4) id 5
LibClamAV debug: bytecode: registered ctx variable at 0x1100f4208 (+648) id 4
LibClamAV debug: bytecode: registered ctx variable at 0x7fadfdf73210 (+744) id 7
LibClamAV debug: bytecode debug: startup: bytecode execution in auto mode
LibClamAV debug: interpreter bytecode run finished in 327us, after executing 96 opcodes
LibClamAV debug: Bytecode: disable status is 0
LibClamAV debug: bytecode: JIT disabled
LibClamAV debug: Cannot prepare for JIT, LLVM is not compiled or not linked
LibClamAV debug: Bytecode: 0 bytecode prepared with JIT, 91 prepared with interpreter, 91 total
LibClamAV debug: in cli_magic_scandesc (reclevel: 0/16)
LibClamAV debug: Recognized binary data
LibClamAV debug: cache_check: c540af550b815231a23eb8b82aff21b9 is negative
LibClamAV debug: in cli_check_mydoom_log()
LibClamAV debug: Matched signature for file type DMG container file at 26760
LibClamAV debug: matcher_run: performing regex matching on full map: 0+27272(27272) >= 27272
LibClamAV debug: hashtab: Freeing hashset, elements: 0, capacity: 0
LibClamAV debug: DMG signature found at 26760
LibClamAV debug: cli_scandmg: Found koly block @ 26760
LibClamAV debug: cli_scandmg: data offset 0 len 18496
LibClamAV debug: cli_scandmg: XML offset 18496 len 8264
LibClamAV debug: cli_scandmg: Extracting into /var/folders/hr/nktrtjjs3tq3b9rt_f9j7bzc0000gp/T//clamav-afe4d5e1579f3822dcc943760840f8de.tmp
LibClamAV debug: cli_map_scan: [18496, +8264)
LibClamAV debug: cli_map_scandesc: [0, +27272), [18496, +8264)
LibClamAV debug: Recognized ASCII text
LibClamAV debug: cache_check: 0bdc6158c0fb41352b1b67de70fc9b70 is negative
LibClamAV debug: matcher_run: performing regex matching on full map: 0+8264(8264) >= 8264
LibClamAV debug: hashtab: Freeing hashset, elements: 0, capacity: 0
LibClamAV debug: in cli_scanscript()
LibClamAV debug: matcher_run: performing regex matching on full map: 0+7363(7363) >= 7363
LibClamAV debug: matcher_run: performing regex matching on full map: 0+7363(7363) >= 7363
LibClamAV debug: hashtab: Freeing hashset, elements: 0, capacity: 0
LibClamAV debug: cli_magic_scandesc: returning 0  at line 2772
LibClamAV debug: cache_add: 0bdc6158c0fb41352b1b67de70fc9b70 (level 0)
LibClamAV debug: cli_scandmg: libxml2 support is compiled out. It is required for full DMG support.
LibClamAV debug: matcher_run: performing regex matching on full map: 0+27272(27272) >= 27272
LibClamAV debug: hashtab: Freeing hashset, elements: 0, capacity: 0
LibClamAV debug: cli_magic_scandesc: returning 0  at line 2772
LibClamAV debug: cache_add: c540af550b815231a23eb8b82aff21b9 (level 0)
/Users/weyer_l/Downloads/----Known virus for testing/Known Virus ziped in a disk image  copy.dmg: OK
LibClamAV debug: Cleaning up phishcheck
LibClamAV debug: Freeing phishcheck struct
LibClamAV debug: Phishcheck cleaned up
----------- SCAN SUMMARY -----------
Known viruses: 6668269
Engine version: 0.100.1
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 0.06 MB
Data read: 0.02 MB (ratio 2.50:1)
Time: 13.099 sec (0 m 13 s)
```

**Comment by fxcoudert** [comment]
Updating to clamav 0.100.2 should fix that issue:

```
$ clamconf|grep -i xml
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE RAR
```

**Comment by taw123** [comment]
Thanks for the quick response but still not fixed....

**Just updated .100.2**
 ```
brewall
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask, homebrew/core).
==> Updated Formulae
clamav ✔            darksky-weather     jenkins             logstash
ballerina           dita-ot             jetty               metabase
bcal                dnscrypt-proxy      jetty-runner        safe
cmake               doctl               jfrog-cli-go        swiftgen
container-diff      elasticsearch       kibana              telegraf
==> Deleted Formulae
asciinema2gif                            casperjs

==> Upgrading 1 outdated package, with result:
clamav 0.100.1 -> 0.100.2
==> Upgrading clamav 
==> Downloading https://homebrew.bintray.com/bottles/clamav-0.100.2.sierra.bottl
######################################################################## 100.0%
==> Pouring clamav-0.100.2.sierra.bottle.tar.gz
==> Caveats
To finish installation & run clamav you will need to edit
the example conf files at /usr/local/etc/clamav/
==> Summary
🍺  /usr/local/Cellar/clamav/0.100.2: 41 files, 3.2MB

```

**brew info clamav**
```
brew info clamav
clamav: stable 0.100.2 (bottled), HEAD
Anti-virus software
https://www.clamav.net/
/usr/local/Cellar/clamav/0.100.1 (45 files, 260.7MB)
  Poured from bottle on 2018-10-03 at 09:36:57
/usr/local/Cellar/clamav/0.100.2 (41 files, 3.2MB) *
  Poured from bottle on 2018-10-04 at 02:17:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/clamav.rb
==> Dependencies
Build: pkg-config ✔
Required: openssl ✔, pcre ✔
Optional: json-c ✘, yara ✘
==> Options
--with-json-c
	Build with json-c support
--with-yara
	Build with yara support
--HEAD
	Install HEAD version
==> Caveats
To finish installation & run clamav you will need to edit
the example conf files at /usr/local/etc/clamav/
```

**Test for LIBXML**

```
Desktop-Air:~ weyer_l$ clamconf|grep -i xml
ScanXMLDOCS = "yes"
```

**Full text of ClamConfig**
```
Desktop-Air:~ weyer_l$ clamconf
Checking configuration files in /usr/local/etc/clamav

Config file: clamd.conf
-----------------------
BlockMax disabled
PreludeEnable disabled
PreludeAnalyzerName disabled
LogFile = "/Library/Logs/ClamAV/clamd.log"
LogFileUnlock disabled
LogFileMaxSize = "2097152"
LogTime = "yes"
LogClean disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
PidFile disabled
TemporaryDirectory disabled
DatabaseDirectory = "/usr/local/share/clamav"
OfficialDatabaseOnly disabled
LocalSocket = "/usr/local/var/run/clamav/clamd.sock"
LocalSocketGroup disabled
LocalSocketMode disabled
FixStaleSocket = "yes"
TCPSocket disabled
TCPAddr disabled
MaxConnectionQueueLength = "200"
StreamMaxLength = "26214400"
StreamMinPort = "1024"
StreamMaxPort = "2048"
MaxThreads = "10"
ReadTimeout = "120"
CommandReadTimeout = "5"
SendBufTimeout = "500"
MaxQueue = "100"
IdleTimeout = "30"
ExcludePath disabled
MaxDirectoryRecursion = "15"
FollowDirectorySymlinks disabled
FollowFileSymlinks disabled
CrossFilesystems = "yes"
SelfCheck = "600"
DisableCache disabled
VirusEvent = "osascript -e "beep 2" && /usr/local/bin/terminal-notifier --args -title "ClamD Scan" -subtitle "Infection detected" -message "%v"  >/dev/null"
ExitOnOOM = "yes"
AllowAllMatchScan = "yes"
Foreground disabled
Debug disabled
LeaveTemporaryFiles disabled
User disabled
Bytecode = "yes"
BytecodeSecurity = "TrustSigned"
BytecodeTimeout = "5000"
BytecodeUnsigned disabled
BytecodeMode = "Auto"
DetectPUA disabled
ExcludePUA disabled
IncludePUA disabled
AlgorithmicDetection = "yes"
ScanPE = "yes"
ScanELF = "yes"
DetectBrokenExecutables disabled
ScanMail = "yes"
ScanPartialMessages disabled
PhishingSignatures = "yes"
PhishingScanURLs = "yes"
PhishingAlwaysBlockCloak disabled
PhishingAlwaysBlockSSLMismatch disabled
PartitionIntersection disabled
HeuristicScanPrecedence disabled
StructuredDataDetection disabled
StructuredMinCreditCardCount = "3"
StructuredMinSSNCount = "3"
StructuredSSNFormatNormal = "yes"
StructuredSSNFormatStripped disabled
ScanHTML = "yes"
ScanOLE2 = "yes"
OLE2BlockMacros disabled
ScanPDF = "yes"
ScanSWF = "yes"
ScanXMLDOCS = "yes"
ScanHWP3 = "yes"
ScanArchive = "yes"
ArchiveBlockEncrypted disabled
ForceToDisk disabled
MaxScanSize = "3145728000"
MaxFileSize = "3145728000"
MaxRecursion = "16"
MaxFiles = "10000"
MaxEmbeddedPE = "10485760"
MaxHTMLNormalize = "10485760"
MaxHTMLNoTags = "2097152"
MaxScriptNormalize = "5242880"
MaxZipTypeRcg = "1048576"
MaxPartitions = "50"
MaxIconsPE = "100"
MaxRecHWP3 = "16"
PCREMatchLimit = "100000"
PCRERecMatchLimit = "5000"
PCREMaxFileSize = "26214400"
ScanOnAccess disabled
OnAccessMountPath disabled
OnAccessIncludePath disabled
OnAccessExcludePath disabled
OnAccessExcludeRootUID disabled
OnAccessExcludeUID disabled
OnAccessMaxFileSize = "5242880"
OnAccessDisableDDD disabled
OnAccessPrevention disabled
OnAccessExtraScanning disabled
DevACOnly disabled
DevACDepth disabled
DevPerformance disabled
DevLiblog disabled
DisableCertCheck disabled

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "2097152"
LogTime = "yes"
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose = "yes"
LogRotate = "yes"
PidFile disabled
DatabaseDirectory = "/usr/local/share/clamav"
Foreground disabled
Debug disabled
UpdateLogFile = "/Library/Logs/ClamAV/freshclam.log"
DatabaseOwner = "_clamav"
Checks = "12"
DNSDatabaseInfo = "current.cvd.clamav.net"
DatabaseMirror = "db.US.big.clamav.net", "database.clamav.net"
PrivateMirror disabled
MaxAttempts = "3"
ScriptedUpdates = "yes"
TestDatabases = "yes"
CompressLocalDatabase disabled
ExtraDatabase disabled
DatabaseCustomURL disabled
HTTPProxyServer disabled
HTTPProxyPort disabled
HTTPProxyUsername disabled
HTTPProxyPassword disabled
HTTPUserAgent disabled
NotifyClamd = "/usr/local/etc/clamav/clamd.conf"
OnUpdateExecute disabled
OnErrorExecute disabled
OnOutdatedExecute disabled
LocalIPAddress disabled
ConnectTimeout = "30"
ReceiveTimeout = "30"
SafeBrowsing disabled
Bytecode = "yes"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.100.2
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 PCRE RAR 

Database information
--------------------
Database directory: /usr/local/share/clamav
Total number of signatures: 0

Platform information
--------------------
uname: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root x86_64
OS: darwin16.7.0, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.8 (1.2.8), compile flags: a9
platform id: 0x04235d5d0800000000040201

Build information
-----------------
Clang: 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2) (4.2.1)
CPPFLAGS: 
CFLAGS: -g -O2  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS: 
LDFLAGS: 
Configure: '--disable-dependency-tracking' '--disable-silent-rules' '--prefix=/usr/local/Cellar/clamav/0.100.2' '--libdir=/usr/local/Cellar/clamav/0.100.2/lib' '--sysconfdir=/usr/local/etc/clamav' '--with-openssl=/usr/local/opt/openssl' '--with-pcre=/usr/local/opt/pcre' '--disable-zlib-vcheck' '--enable-llvm=no' '--without-libjson' '--disable-yara' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12' --enable-ltdl-convenience
sizeof(void*) = 8
Engine flevel: 93, dconf: 93

```

**Comment by fxcoudert** [comment]
Confirmed that it is a problem, but only on Sierra, by examining all bottles. On Mojave and High Sierra:

```
$ otool -L ./clamscan|grep -i xml    
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
```

while on Sierra libxml2 is not linked.

@taw123 Can you do a build from source (`brew install -s --verbose clamav`) and give us the link to `brew gist-logs`?

**Comment by taw123** [comment]
Given package was already installed assumed you wanted me to do a 
`brew reinstall -s --verbose clamav`

Which I did.

Link to gist-log: [https://gist.github.com/9f86cf801dc3d21896cae8c947a62d3c](url)

**Comment by fxcoudert** [comment]
Homebrew doesn't change file ownership/permission, because it is installed in my settings where users don't have permission to do that (or don't want to do that).

**Comment by fxcoudert** [comment]
The problem happens during configure:

```
configure:17851: checking for libxml2 installation
configure:17887: result: /usr
configure:17899: checking xml2-config version
configure:17903: result: 2.9.4
configure:17917: checking for xmlreader.h in /usr
configure:17924: result: found
configure:17935: checking for xmlTextReaderRead in -lxml2
configure:17960: clang -o conftest -g -O2  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2  -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm conftest.c -lxml2 -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm  >&5
ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
```

**Comment by fxcoudert** [comment]
I'm trying a fix in #33209

**Comment by taw123** [comment]
I looked at  [
https://github.com/Homebrew/homebrew-core/pull/33209](url) looks like issue is still present.

Is there a workaround short of trying to re-install .99.2?

Thanks.

**Comment by taw123** [comment]
I looked at 
https://github.com/Homebrew/homebrew-core/pull/33209 looks like issue is still present.

Is there a workaround short of trying to re-install .99.2?

Thanks.

**Comment by BenjaminHCCarr** [comment]
ClamAV 0.101.0 fails to build on `high sierra`
```
benc$ clamconf|grep -i xml
ScanXMLDOCS = "yes"
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE RAR
```

```
libtool: link: rm -f ".libs/libclamavS.c" ".libs/libclamav.nm" ".libs/libclamav.nmS" ".libs/libclamav.nmT" ".libs/libclamav.nmI"
libtool: link: clang -dynamiclib  -o .libs/libclamav.9.dylib  .libs/libclamav_la-matcher-ac.o .libs/libclamav_la-matcher-bm.o .libs/libclamav_la-matcher-hash.o .libs/libclamav_la-matcher.o .libs/libclamav_la-others.o .libs/libclamav_la-readdb.o .libs/libclamav_la-cvd.o .libs/libclamav_la-dsig.o .libs/libclamav_la-scanners.o .libs/libclamav_la-textdet.o .libs/libclamav_la-filetypes.o .libs/libclamav_la-rtf.o .libs/libclamav_la-blob.o .libs/libclamav_la-mbox.o .libs/libclamav_la-message.o .libs/libclamav_la-table.o .libs/libclamav_la-text.o .libs/libclamav_la-ole2_extract.o .libs/libclamav_la-vba_extract.o .libs/libclamav_la-msexpand.o .libs/libclamav_la-pe.o .libs/libclamav_la-pe_icons.o .libs/libclamav_la-disasm.o .libs/libclamav_la-upx.o .libs/libclamav_la-htmlnorm.o .libs/libclamav_la-libmspack.o .libs/libclamav_la-rebuildpe.o .libs/libclamav_la-petite.o .libs/libclamav_la-wwunpack.o .libs/libclamav_la-unsp.o .libs/libclamav_la-aspack.o .libs/libclamav_la-packlibs.o .libs/libclamav_la-fsg.o .libs/libclamav_la-mew.o .libs/libclamav_la-upack.o .libs/libclamav_la-line.o .libs/libclamav_la-untar.o .libs/libclamav_la-unzip.o .libs/libclamav_la-ooxml.o .libs/libclamav_la-inflate64.o .libs/libclamav_la-special.o .libs/libclamav_la-binhex.o .libs/libclamav_la-is_tar.o .libs/libclamav_la-tnef.o .libs/libclamav_la-autoit.o .libs/libclamav_la-unarj.o .libs/libclamav_la-bzlib.o .libs/libclamav_la-nulsft.o .libs/libclamav_la-infblock.o .libs/libclamav_la-pdf.o .libs/libclamav_la-pdfng.o .libs/libclamav_la-pdfdecode.o .libs/libclamav_la-spin.o .libs/libclamav_la-yc.o .libs/libclamav_la-elf.o .libs/libclamav_la-sis.o .libs/libclamav_la-uuencode.o .libs/libclamav_la-phishcheck.o .libs/libclamav_la-phish_domaincheck_db.o .libs/libclamav_la-phish_whitelist.o .libs/libclamav_la-regex_list.o .libs/libclamav_la-regex_suffix.o .libs/libclamav_la-entconv.o .libs/libclamav_la-hashtab.o .libs/libclamav_la-dconf.o .libs/libclamav_la-lzma_iface.o .libs/libclamav_la-7z_iface.o .libs/libclamav_la-7zAlloc.o .libs/libclamav_la-7zBuf.o .libs/libclamav_la-7zBuf2.o .libs/libclamav_la-7zCrc.o .libs/libclamav_la-7zDec.o .libs/libclamav_la-7zFile.o .libs/libclamav_la-7zIn.o .libs/libclamav_la-7zStream.o .libs/libclamav_la-Bcj2.o .libs/libclamav_la-Bra.o .libs/libclamav_la-Bra86.o .libs/libclamav_la-Lzma2Dec.o .libs/libclamav_la-LzmaDec.o .libs/libclamav_la-Ppmd7.o .libs/libclamav_la-Ppmd7Dec.o .libs/libclamav_la-Xz.o .libs/libclamav_la-XzCrc64.o .libs/libclamav_la-XzDec.o .libs/libclamav_la-XzIn.o .libs/libclamav_la-Delta.o .libs/libclamav_la-BraIA64.o .libs/libclamav_la-CpuArch.o .libs/libclamav_la-7zCrcOpt.o .libs/libclamav_la-explode.o .libs/libclamav_la-textnorm.o .libs/libclamav_la-dlp.o .libs/libclamav_la-js-norm.o .libs/libclamav_la-uniq.o .libs/libclamav_la-version.o .libs/libclamav_la-mpool.o .libs/libclamav_la-filtering.o .libs/libclamav_la-fmap.o .libs/libclamav_la-perflogging.o .libs/libclamav_la-bytecode.o .libs/libclamav_la-bytecode_vm.o .libs/libclamav_la-cpio.o .libs/libclamav_la-macho.o .libs/libclamav_la-ishield.o .libs/libclamav_la-bytecode_api.o .libs/libclamav_la-bytecode_api_decl.o .libs/libclamav_la-cache.o .libs/libclamav_la-bytecode_detect.o .libs/libclamav_la-events.o .libs/libclamav_la-adc.o .libs/libclamav_la-dmg.o .libs/libclamav_la-xar.o .libs/libclamav_la-xdp.o .libs/libclamav_la-mbr.o .libs/libclamav_la-gpt.o .libs/libclamav_la-apm.o .libs/libclamav_la-prtn_intxn.o .libs/libclamav_la-json_api.o .libs/libclamav_la-xz_iface.o .libs/libclamav_la-sf_base64decode.o .libs/libclamav_la-hfsplus.o .libs/libclamav_la-swf.o .libs/libclamav_la-jpeg.o .libs/libclamav_la-png.o .libs/libclamav_la-iso9660.o .libs/libclamav_la-arc4.o .libs/libclamav_la-rijndael.o .libs/libclamav_la-crtmgr.o .libs/libclamav_la-asn1.o .libs/libclamav_la-fpu.o .libs/libclamav_la-stats.o .libs/libclamav_la-www.o .libs/libclamav_la-stats_json.o .libs/libclamav_la-hostid.o .libs/libclamav_la-openioc.o .libs/libclamav_la-msdoc.o .libs/libclamav_la-matcher-pcre.o .libs/libclamav_la-regex_pcre.o .libs/libclamav_la-msxml.o .libs/libclamav_la-msxml_parser.o .libs/libclamav_la-tiff.o .libs/libclamav_la-hwp.o .libs/libclamav_la-lzwdec.o .libs/libclamav_la-matcher-byte-comp.o .libs/libclamav_la-fp_add.o .libs/libclamav_la-fp_add_d.o .libs/libclamav_la-fp_addmod.o .libs/libclamav_la-fp_cmp.o .libs/libclamav_la-fp_cmp_d.o .libs/libclamav_la-fp_cmp_mag.o .libs/libclamav_la-fp_sub.o .libs/libclamav_la-fp_sub_d.o .libs/libclamav_la-fp_submod.o .libs/libclamav_la-s_fp_add.o .libs/libclamav_la-s_fp_sub.o .libs/libclamav_la-fp_radix_size.o .libs/libclamav_la-fp_read_radix.o .libs/libclamav_la-fp_read_signed_bin.o .libs/libclamav_la-fp_read_unsigned_bin.o .libs/libclamav_la-fp_reverse.o .libs/libclamav_la-fp_s_rmap.o .libs/libclamav_la-fp_signed_bin_size.o .libs/libclamav_la-fp_to_signed_bin.o .libs/libclamav_la-fp_to_unsigned_bin.o .libs/libclamav_la-fp_toradix.o .libs/libclamav_la-fp_toradix_n.o .libs/libclamav_la-fp_unsigned_bin_size.o .libs/libclamav_la-fp_cnt_lsb.o .libs/libclamav_la-fp_count_bits.o .libs/libclamav_la-fp_div_2.o .libs/libclamav_la-fp_div_2d.o .libs/libclamav_la-fp_lshd.o .libs/libclamav_la-fp_mod_2d.o .libs/libclamav_la-fp_rshd.o .libs/libclamav_la-fp_div.o .libs/libclamav_la-fp_div_d.o .libs/libclamav_la-fp_mod.o .libs/libclamav_la-fp_mod_d.o .libs/libclamav_la-fp_2expt.o .libs/libclamav_la-fp_exptmod.o .libs/libclamav_la-fp_ident.o .libs/libclamav_la-fp_set.o .libs/libclamav_la-fp_montgomery_calc_normalization.o .libs/libclamav_la-fp_montgomery_reduce.o .libs/libclamav_la-fp_montgomery_setup.o .libs/libclamav_la-fp_mul.o .libs/libclamav_la-fp_mul_comba.o .libs/libclamav_la-fp_mul_2.o .libs/libclamav_la-fp_mul_2d.o .libs/libclamav_la-fp_mul_comba_12.o .libs/libclamav_la-fp_mul_comba_17.o .libs/libclamav_la-fp_mul_comba_20.o .libs/libclamav_la-fp_mul_comba_24.o .libs/libclamav_la-fp_mul_comba_28.o .libs/libclamav_la-fp_mul_comba_3.o .libs/libclamav_la-fp_mul_comba_32.o .libs/libclamav_la-fp_mul_comba_4.o .libs/libclamav_la-fp_mul_comba_48.o .libs/libclamav_la-fp_mul_comba_6.o .libs/libclamav_la-fp_mul_comba_64.o .libs/libclamav_la-fp_mul_comba_7.o .libs/libclamav_la-fp_mul_comba_8.o .libs/libclamav_la-fp_mul_comba_9.o .libs/libclamav_la-fp_mul_comba_small_set.o .libs/libclamav_la-fp_mul_d.o .libs/libclamav_la-fp_mulmod.o .libs/libclamav_la-fp_invmod.o .libs/libclamav_la-fp_sqr.o .libs/libclamav_la-fp_sqr_comba_12.o .libs/libclamav_la-fp_sqr_comba_17.o .libs/libclamav_la-fp_sqr_comba_20.o .libs/libclamav_la-fp_sqr_comba_24.o .libs/libclamav_la-fp_sqr_comba_28.o .libs/libclamav_la-fp_sqr_comba_3.o .libs/libclamav_la-fp_sqr_comba_32.o .libs/libclamav_la-fp_sqr_comba_4.o .libs/libclamav_la-fp_sqr_comba_48.o .libs/libclamav_la-fp_sqr_comba_6.o .libs/libclamav_la-fp_sqr_comba_64.o .libs/libclamav_la-fp_sqr_comba_7.o .libs/libclamav_la-fp_sqr_comba_8.o .libs/libclamav_la-fp_sqr_comba_9.o .libs/libclamav_la-fp_sqr_comba_generic.o .libs/libclamav_la-fp_sqr_comba_small_set.o .libs/libclamav_la-fp_sqrmod.o .libs/libclamavS.o  -Wl,-force_load,./.libs/libclamav_nocxx.a -Wl,-force_load,./.libs/libclamav_internal_utils.a  -L/usr/local/opt/openssl/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib -lxml2 -lpthread -licucore -lm -L/usr/local/Cellar/pcre/8.42/lib -lbz2 -lltdl /private/tmp/clamav-20181206-8141-fcb1od/clamav-0.101.0/libclamav/.libs/libclammspack.dylib -lssl -lcrypto -lz -lpcre  -g -O2 -Wl,-M -Wl,../libclamav/libclamav.map   -install_name  /usr/local/Cellar/clamav/0.101.0/lib/libclamav.9.dylib -compatibility_version 10 -current_version 10.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_cli_strndup", referenced from:
      _cli_get_filepath_from_filedesc in libclamav_internal_utils.a(libclamav_internal_utils_la-others_common.o)
  "_cli_strnlen", referenced from:
      _cli_get_filepath_from_filedesc in libclamav_internal_utils.a(libclamav_internal_utils_la-others_common.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libclamav.la] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

gist: https://gist.github.com/BenjaminHCCarr/9917fb4a42253de87f1323e98d977e76
