### ISSUE TITLE
PHP 7.3 seg faults when using sodium_crypto_pwhash_str

### ISSUE THREAD

**Issue by phpeek** [Homebrew/homebrew-core#45074]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Symfony PHP framework is using sodium extension (when available) to encode users passwords.

- What happened (include command output)

```sh
> php -r "sodium_crypto_pwhash_str('foo', 4, 67108864);"                                                                                     
[1]     3947 segmentation fault  php -r "sodium_crypto_pwhash_str('foo', 4, 67108864);"
```
- What you expected to happen

Function should return proper password hash.

- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew install php
```

```sh
php -r "sodium_crypto_pwhash_str('foo', 4, 67108864);"
```

**Comment by LogicException** [comment]
Same here, maybe it is related to: https://github.com/jedisct1/libsodium/issues/881

**Comment by phpeek** [comment]
@LogicException Yes, that was my assumption too.

If You're struggling with this, my advice for now would be to disable `sodium` extension and rebuild php from source.



What I did for now:

```sh
brew edit php
```

Removed this line https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb#L152

```sh
brew reinstall -s php
```

If You're - hopefully - not reliant on this extension, You should be fine until this issue is resolved.

**Comment by LogicException** [comment]
@phpeek thank's for the workaround, but switching encryption algorithm in my symphony dev env is way more easier ;-)

**Comment by mennoterlaak** [comment]
Using the stable branche of libsodium instead of the release package worked for me. I edited the brew formula a bit to build the stable branche using the head parameter as workaround.

`  head do
    url "https://github.com/jedisct1/libsodium.git", :branch => "stable"
    depends_on "autoconf" => :build
    depends_on "automake" => :build
    depends_on "libtool" => :build
  end `

**Comment by SMillerDev** [comment]
Could you report that upstream? It seems important for them to know that their release is broken on macOS.

**Comment by mennoterlaak** [comment]
> Could you report that upstream? It seems important for them to know that their release is broken on macOS.

See https://github.com/jedisct1/libsodium/issues/881 I only applied solution 2 under “What can you do?” They are aware.

**Comment by phpeek** [comment]
Appears that this issue has been fixed by Xcode 11.2 release. Closing.

**Comment by kamilmaliszewski** [comment]
I did all points from this issue, but it doesnt help for me. After upgrade to MacOS Catalina 10.15.1, then Xcode to 11.2 I still have this error

`[1]    13177 segmentation fault  php -r "sodium_crypto_pwhash_str('foo', 4, 67108864);"`

PHP 7.2 + PHP 7.3 which use libsodium

**Comment by LogicException** [comment]
@kamilmaliszewski you can try @phpeek's answer (https://github.com/Homebrew/homebrew-core/issues/45074#issuecomment-542373915 ), this workaround solved the problem for me

**Comment by kamilmaliszewski** [comment]
@LogicException but looking on this answer, he is removing sodium from PHP lib. So in the result this metod `sodium_crypto_pwhash_str` wlill stop working? I need this method working

**Comment by LogicException** [comment]
@kamilmaliszewski yes, you're right, sorry 🥺 that was not the full story. I've removed libsodium like @phpeek described in his answer and **than rebuild it** like @mennoterlaak described in https://github.com/Homebrew/homebrew-core/issues/45074#issuecomment-542736213

**Comment by phpeek** [comment]
@kamilmaliszewski Are You sure You've rebuild PHP after upgrading Xcode ?

```
brew reinstall -s php
```

Make sure You won't skip `-s` flag.

**Comment by kamilmaliszewski** [comment]
@phpeek yep, I did it before, but I started it also right now `brew reinstall -s php`, then restart apache and php and... still the same. 

`php -r "sodium_crypto_pwhash_str('foo', 4, 67108864);"
[1]    94573 segmentation fault  php -r "sodium_crypto_pwhash_str('foo', 4, 67108864);"`

I have MacOS Catalina 10.15.1
Xcode 11.2 (11B52)
PHP 7.3.11 
Httpd 2.4.41
Libsodium 1.0.18

Not have idea what to do to fix it

**Comment by kamilmaliszewski** [comment]
@phpeek do you have also the newest php version? Maybe you have any older? Can you check?

**Comment by phpeek** [comment]
@kamilmaliszewski Sorry for the confusion. You were right. `php` still segfaults with latest `1.0.18` version of libsodium.

If Your app depends on `sodium` extension, then You have to rely on workaround suggested by @mennoterlaak - https://github.com/Homebrew/homebrew-core/issues/45074#issuecomment-542736213.

```sh
brew unlink libsodium
brew edit libsodium
```

Point `HEAD` to `stable` branch as suggested in mentioned comment and do

```sh
brew install --HEAD libsodium
```

It's working for me.

**Comment by phpeek** [comment]
I've issued PR for `libsodium` formula - https://github.com/Homebrew/homebrew-core/pull/46604 in order for it to be fetched from stable release tarball. This should fix the issue and workaround won't be necessary.

**Comment by kamilmaliszewski** [comment]
@phpeek your solution works for me. After add this `":branch => "stable"` and reinstall libsodium everything is fine. `sodium_crypto_pwhash_str` is used by Magento2 when you are trying to login into admin panel, so I thnik soon will be more pepole here :)

**Comment by Bo98** [comment]
libsodium has been rebuilt using Xcode 11.2 (and a different source url). Hopefully this should be working now. Let me know if it isn't and I'll reopen.
