### ISSUE TITLE
QEMU build fails with "Undefined symbols for architecture x86_64” in sdl.o

### ISSUE THREAD

**Issue by karanlyons** [Homebrew/homebrew-core#4707]
Specifically:

```
Undefined symbols for architecture x86_64:
  "_XFree", referenced from:
      _sdl_keyevent_to_keycode in sdl.o
  "_XGetAtomName", referenced from:
      _sdl_keyevent_to_keycode in sdl.o
  "_XkbFreeKeyboard", referenced from:
      _sdl_keyevent_to_keycode in sdl.o
  "_XkbGetKeyboard", referenced from:
      _sdl_keyevent_to_keycode in sdl.o
```

[Here’re the logs](https://gist.github.com/karanlyons/fbe4d6584717bfb31a2958f21206fc66)

It’s possible we’re just missing libX11?

**Comment by dunn** [comment]
If there's an undeclared X11 dependency, that either needs to be disabled or the formula needs to be in our X11 tap, unfortunately.

**Comment by zmwangx** [comment]
FWIW here's a grep of `X11/` on their cgit: http://git.qemu-project.org/?p=qemu.git&a=search&st=grep&s=X11%2F.

It seems that `XKBlib.h` is included if building with sdl and `SDL_VIDEO_DRIVER_X11` is defined.

**Comment by karanlyons** [comment]
Yeah, so this X11 is only needed with the `--with-sdl` flag, but it still doesn’t build even despite having XQuartz installed (this is likely a search path issue, or at least I hope).

But we may first need to deal with the X11 tap portion of this issue. Given that this formula only has the X11 dependency when built with a flag (and not as a hard requirement for the default build) what’s the preferred way to handle it?

**Comment by zmwangx** [comment]
Actually, if you follow my previous link, `--with-gdk+` might need X11 too.

Could you please try

```ruby
depends_on :x11 if build.with?("sdl") || build.with?("gdk+")
```

and see if it works?

**Comment by karanlyons** [comment]
Thus far I know that `brew install qemu --with-libssh2 --with-vde` will build cleanly.

brew install qemu --with-libssh2 --with-vde --with-sdl` gives the same previously reported errors (concerning, since this time around I tried with `LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/opt/X11/lib`).

brew install qemu --with-libssh2 --with-vde --with-gtk+` throws the error “ERROR: Cocoa and GTK UIs cannot both be enabled at once”, which I think `--with-sdl` would do as well if it could get that far (http://git.qemu-project.org/?p=qemu.git;a=blob;f=configure#l1706).

So, as a tangential issue, I’m pretty sure having `--enable-sdl`/`--enable-gtk` in the flags to configure should also then pass `--disable-cocoa` as opposed to `--enable-cocoa` as it currently does.

**Comment by zmwangx** [comment]
No, there's already

```ruby
    # Cocoa and SDL UIs cannot both be enabled at once.
    if build.with? "sdl"
      args << "--enable-sdl" << "--disable-cocoa"
    else
      args << "--enable-cocoa" << "--disable-sdl"
    end
```

in the formula. Just need to do the same for `gdk+`.

That's not the main concern though. Have you tried adding

```ruby
depends_on :x11 if build.with?("sdl") || build.with?("gdk+")
```

then `brew install qemu --with-sdl`?

**Comment by karanlyons** [comment]
I’ve patched the formula adding `depends_on :x11 if build.with?("sdl") || build.with?("gtk+”)` and modifying `install` thusly:

```ruby
  def install
    ENV["LIBTOOL"] = "glibtool"

    args = %W[
      --prefix=#{prefix}
      --cc=#{ENV.cc}
      --host-cc=#{ENV.cc}
      --disable-bsd-user
      --disable-guest-agent
    ]

    # Cocoa and SDL/gtk+ UIs cannot both be enabled at once.
    if build.with?("sdl") || build.with?("gtk+")
      args << "--disable-cocoa"
    else
      args << "--enable-cocoa"
    end

    args << (build.with?("vde") ? "--enable-vde" : "--disable-vde")
    args << (build.with?("sdl") ? "--enable-sdl" : "--disable-sdl")
    args << (build.with?("gtk+") ? "--enable-gtk" : "--disable-gtk")
    args << (build.with?("libssh2") ? "--enable-libssh2" : "--disable-libssh2")

    system "./configure", *args
    system "make", "V=1", "install"
  end
```

The latter changes properly disable cocoa for both SDL *and* gtk+. Given these changes, here’s what I see:

```
brew install qemu --with-libssh2 --with-vde: Builds.
    Resulting configure flags: --disable-bsd-user --disable-guest-agent --disable-cocoa --enable-vde --disable-sdl --enable-gtk --enable-libssh2

brew install qemu --with-libssh2 --with-vde --with-gtk+: Builds.
    Resulting configure flags: --disable-bsd-user --disable-guest-agent --disable-cocoa --enable-vde --disable-sdl --enable-gtk --enable-libssh2

brew install qemu --with-libssh2 --with-vde --with-sdl: Fails as originally noted.
    Resulting configure flags: --disable-bsd-user --disable-guest-agent --disable-cocoa --enable-vde --enable-sdl --disable-gtk --enable-libssh2
```

**Comment by zmwangx** [comment]
> brew install qemu --with-libssh2 --with-vde --with-sdl: Fails as originally noted.

Okay, no idea then.

**Comment by karanlyons** [comment]
We should at least add the changes to properly disable cocoa, but I’ve still no idea what’s causing `--with-sdl` to fail even when I’ve confirmed X11 is installed. But perhaps that discussion should be moved to the X11 tap?

**Comment by zmwangx** [comment]
Optional `:x11` deps are acceptable (at the moment) in core, although we do want to burn them in fire.

> We should at least add the changes to properly disable cocoa

Yes, please submit a PR.

**Comment by zmwangx** [comment]
I guess sdl and gdk+ can't live in peace either? Might need to `odie` when both are specified.

**Comment by zmwangx** [comment]
Checked the source code, actually no, please ignore the comment immediately above.

**Comment by karanlyons** [comment]
Yeah, cocoa’s the only bad player there. I’ve submitted a PR for the easier fix, but I’m avoiding the added X11 dependency since thus far that doesn’t appear to be the only problem with `--with-sdl`. But at least we fixed *something*.

**Comment by zmwangx** [comment]
No, don't do anything about X11 yet.

**Comment by JCount** [comment]
This might be fixed in `qemu 2.8.0` that was just merged. #9144 

I tried to replicate the `brew install qemu --with-libssh2 --with-vde --with-sdl` failure, but was unable to do so in my 10.11.6 VM building qemu 2.8.0.

**Comment by JCount** [comment]
I just tried building it on my main macOS sierra installation and ran into this issue myself when trying to install `--with-sdl`.

Any thoughts @zmwangx since you were working to address this issue before?

**Comment by zmwangx** [comment]
It's been too long, so no thoughts.

**Comment by JCount** [comment]
ok, thanks thought I would ask just in case. 👍

**Comment by JCount** [comment]
I believe I may have solved this. If `sdl` was built `--with-x11` this failure occurs for me, using vanilla `sdl` seems to be the solution.

**Comment by JCount** [comment]
This should be fixed by the switch to `sdl2` in #9173.

**Comment by EugenMayer** [comment]
how would i test this, added you as a tap, installing `brew install jcount/core/qemu --with-sdl` does still not work

**Comment by JCount** [comment]
@EugenMayer It is now changed in `homebrew/core` so all you should need to do, after running `brew update`, is run `brew install qemu --with-sdl2`.
