### ISSUE TITLE
solr 8.4.1 broken since commit of #50494

### ISSUE THREAD

**Issue by mkalkbrenner** [Homebrew/homebrew-core#50537]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew upgrade

## What happened (include command output)

Solr doesn't start anymore since updated from 8.4.1 to 8.4.1_1, due to the commit of #50494

<details>
  <summary>Command output</summary>
  <pre>

  $ solr start

Solr server directory /usr/local/Cellar/solr/8.4.1_1/libexec/server not found!

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install solr
solr start

**Comment by SMillerDev** [comment]
Should be fixed now

**Comment by mkalkbrenner** [comment]
@SMillerDev fixed by whioch commit?

**Comment by mkalkbrenner** [comment]
It is not fixed!

I assume the problem is this new line:
```rb
bin.env_script_all_files libexec/"bin", :JAVA_HOME => Formula["openjdk"].opt_prefix
```

Unlike other formulars "libexec" really exists as a folder in solr.

**Comment by SMillerDev** [comment]
Oh sorry, I misread the commit message above as a merge to `homebrew/core`. And didn't spot that you made it.

**Comment by mkalkbrenner** [comment]
@SMillerDev no problem. My commit didn't solve the issue. Unfortunately I'm not a ruby developer. So my experimental commit in my fork didn't solve the issue.

In the console output I posted in the description you see this eror message:
```
Solr server directory /usr/local/Cellar/solr/8.4.1_1/libexec/server not found!
```

So the env wrapper script logic messes up the path. The path to the server directory has to be
`/usr/local/Cellar/solr/8.4.1_1/libexec/server`, so without `libexec`!

**Comment by SMillerDev** [comment]
@reitermarkus any ideas?

**Comment by mkalkbrenner** [comment]
I commented #50540

What do you think about my suggestion there to adjust the symlink?

**Comment by mkalkbrenner** [comment]
Please have a look at #50684 
It stops the problematic patching of solr config files and examples.
BTW examples where broken since a longer time because of using `/usr/local/var/lib/solr`. Therefore I dropped the support for the examples.
I tested the more simple approach to force openjdk implemented my PR with `solr start` and it works. And all my existing collections and cores work as well without modification.
