### ISSUE TITLE
Cannot update paths and switch to branch 'v1.0.2' at the same time

### ISSUE THREAD

**Issue by thibmaek** [Homebrew/homebrew-core#5118]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Running `brew update && brew upgrade --all` produced the following git errors in output:

```console
Checking out v1.0.2 in /usr/local/Homebrew...
To checkout master in /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git checkout master
Checking out v1.0.2 in /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
To checkout master in /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask run:
  'cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.2' at the same time.
Did you intend to checkout 'refs/tags/1.0.2' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.2
Checking out v1.0.2 in /usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions...
To checkout master in /usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions run:
  'cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.2' at the same time.
Did you intend to checkout 'refs/tags/1.0.2' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.2
Checking out v1.0.2 in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
To checkout master in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.2' at the same time.
Did you intend to checkout 'refs/tags/1.0.2' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.2
Checking out v1.0.2 in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes...
To checkout master in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes && git checkout master
fatal: Cannot update paths and switch to branch 'v1.0.2' at the same time.
Did you intend to checkout 'refs/tags/1.0.2' which can not be resolved as commit?
fatal: Needed a single revision
```

**Comment by DomT4** [comment]
This should have been solved in the last few days. If you keep seeing it after one or two more `brew update`s please shout.

**Comment by International** [comment]
@DomT4 The error message is still present, and appears everytime I do a bundle update:
```
fatal: Cannot update paths and switch to branch 'v1.0.7' at the same time.
Did you intend to checkout 'refs/tags/1.0.7' which can not be resolved as commit?
fatal: Needed a single revision
invalid upstream refs/tags/1.0.7
```
Usually I run `brew update` once every few days, and the branch and tag appear with incrementing numbers.

**Comment by MikeMcQuaid** [comment]
@International `Can I see your `git branch`, `git tag --list` and `brew config` output? Also, https://github.com/Homebrew/homebrew-core#update-bug may fix your problem.

**Comment by International** [comment]
@MikeMcQuaid thank you, your link fixed it!
