### ISSUE TITLE
Formula related questions

### ISSUE THREAD

**Issue by BarryWheeler** [Homebrew/homebrew-core#8135]
Hi!
I have bunch of questions related to formula (particularly this one: [phantomjs.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/phantomjs.rb) )

So:

1. It depends from XCode (depends_on :xcode => :build) - is it really necessary? Is Command Line Tools not enough?
2. According to their site, they have compiled (static build) version of this package for macOS, may be it will be better to provide already compiled version instead building it from scratch, because not everybody want full blown XCode app installed.
3. For example, I downloaded package from their site and added it to my PATH, but in homebrew, there is another formula which requires phantomjs installed, as I understand - via homebrew, and it will not find already installed package, which is installed, but NOT via homebrew, right? Is it possible to force homebrew package, which requires phantomjs, to see installed phantomjs? Or may be there is another ways besides from XCode installation?

I am trying to avoid XCode full package installation.

**Comment by BarryWheeler** [comment]
Fixed typos

**Comment by BarryWheeler** [comment]
And I found this discussion: [link](https://github.com/Homebrew/legacy-homebrew/pull/11225)

as I understand, earlier, homebrew had delivered a compiled binary. Do not know, what and why this way was changed.

**Comment by ploxiln** [comment]
If `depends_on :xcode => :build`, then yes, someone determined that it really needed Xcode to build. Most formulas don't have that.

But you still don't necessarily need to build it, when installing from homebrew. You can still avoid Xcode. That formula (like most) has "Bottles", which are built binary packages, which are used by default if you have not used any custom build options when installing that formula, or any of its dependencies (or recursive deps).

**Comment by ploxiln** [comment]
re: question 3: not easily. you can do `brew install --ignore-dependencies ...` but it may not work, and even if it does, you'll probably end up fighting with it again and again in the future (whenever installing anything which depends on the thing that depends on phantomjs, or upgrades to any of these things).

**Comment by BarryWheeler** [comment]
Lack of knowledge is bad.
Well, @ploxiln - you was right! Phantomjs and related formulas successfully installed without asking to be compiled with XCode. Cool!

My fallback option was to use Cellar, as I understand, you can put any 3rd party binary into Cellar and just link it to bin directory. This is what I planned to do. Glad that everything is ok now.

**Comment by MikeMcQuaid** [comment]
> It depends from XCode (depends_on :xcode => :build) - is it really necessary?

It was at some point. If it is no longer: please submit a pull-request to remove it. [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

> According to their site, they have compiled (static build) version of this package for macOS, may be it will be better to provide already compiled version instead building it from scratch, because not everybody want full blown XCode app installed.

You can (and have) downloaded it yourself manually.

> Is it possible to force homebrew package, which requires phantomjs, to see installed phantomjs? Or may be there is another ways besides from XCode installation?

No, sorry. We'd recommend using the default Homebrew installation location and a support macOS version which we support (Yosemite and up) and provide a binary package for.
