### ISSUE TITLE
weechat failed to build on 10.11.6

### ISSUE THREAD

**Issue by lparsons** [Homebrew/homebrew-core#8452]
`brew gist-logs weechat`: https://gist.github.com/995b82718c70369eb2bf60dbe6806fe2

**Comment by ilovezfs** [comment]
Yup.

**Comment by marmot1123** [comment]
I had the same situation.
I solved the situation by removing `anaconda` from my `$PATH`.
Concretely, I search in `~/.zshrc`, `~/.bashrc`, and `~/.bash_profile`.
Anaconda may add an export sentence to `~/.bash_profile` when it was installed.
Then, I executed `brew upgrade weechat` and I could upgrade weechat.

**Comment by ilovezfs** [comment]
nope, no anaconda in sight here.

**Comment by ilovezfs** [comment]
Appears to be caused by `--with-ruby `

**Comment by ilovezfs** [comment]
Should be fixed if you brew update.

**Comment by sprig** [comment]
Not for me: https://gist.github.com/anonymous/15ef53e0311437d7bc6f60f604556d0d

**Comment by kejadlen** [comment]
I still have this issue as well. Is this because I only use Ruby through `chruby` and don't `brew install ruby`?

**Comment by ilovezfs** [comment]
@kejadlen probably.

**Comment by kejadlen** [comment]
Oof. Is there a way to coax weechat into looking at the right include path?

**Comment by sprig** [comment]
P.S.
{{{brew update && brew upgrade && brew cleanup}}} fixed the problems in my case. Mysterious problem...
